import type { MathNode } from '../types'

export const ALGEBRAIC_GEOMETRY_NODES: MathNode[] = [
  // ── Affine geometry and the algebra–geometry dictionary ────────────────────
  {
    id: 'affine-variety',
    label: 'Affine Variety',
    title: 'Affine Variety',
    kind: 'definition',
    tags: ['Algebraic Geometry'],
    dependencies: ['polynomial', 'field', 'ideal'],
    description: String.raw`The subject begins with the solution sets of polynomial equations. Fix a field $k$ and ask: which points of $k^n$ make a given family of polynomials simultaneously vanish? Lines, conics, the cuspidal cubic $y^2 = x^3$, and the curve $y^2 = x^3 - x$ are all of this form. The remarkable program of algebraic geometry is to study such geometric sets entirely through the algebra of the polynomials that cut them out, so that geometric questions become questions about ideals and rings.`,
    definition: String.raw`Let $k$ be a field. For a set $S \subseteq k[x_1, \dots, x_n]$ of **polynomials**, its **zero locus** is
$$V(S) = \{\,x \in k^n : f(x) = 0 \text{ for all } f \in S\,\}.$$
An **affine algebraic set** is a subset of $k^n$ of the form $V(S)$ for some $S$; since $V(S) = V(I)$ for the ideal $I = (S)$ generated by $S$, one may always take $S$ to be an ideal. An **affine variety** is an affine algebraic set (some authors reserve the word for the *irreducible* ones; see **irreducible-variety**). Dually, for a subset $X \subseteq k^n$ the **vanishing ideal** is $I(X) = \{\,f \in k[x_1, \dots, x_n] : f|_X = 0\,\}$, an ideal that is automatically radical.`,
  },
  {
    id: 'zariski-topology',
    label: 'Zariski Topology',
    title: 'Zariski Topology',
    kind: 'definition',
    tags: ['Algebraic Geometry'],
    dependencies: ['affine-variety', 'topological-space'],
    description: String.raw`Algebraic sets are closed under finite unions and arbitrary intersections, exactly the closure properties asked of the closed sets of a topology. Declaring them the closed sets gives the Zariski topology, the native topology of algebraic geometry. It is extremely coarse — on $k^n$ (or any irreducible variety) any two nonempty open sets meet, so every nonempty open set is dense — and is built from polynomials rather than distance: it is the topology in which regular maps are continuous and in which dimension is defined.`,
    definition: String.raw`The **Zariski topology** on $k^n$ takes the affine algebraic sets $V(I)$ as its closed sets; a variety $X \subseteq k^n$ inherits the **subspace** Zariski topology, whose closed sets are the algebraic subsets of $k^n$ contained in $X$.`,
    proof: String.raw`**The sets $\{V(I)\}$ are the closed sets of a topology on $k^n$.** We verify the axioms of a **topological space**. The whole space and the empty set are closed: $V((0)) = k^n$ and $V((1)) = \varnothing$. *Arbitrary intersections:* for ideals $\{I_\alpha\}$, $\bigcap_\alpha V(I_\alpha) = \{x : f(x) = 0\ \forall f \in \bigcup_\alpha I_\alpha\} = V\bigl(\sum_\alpha I_\alpha\bigr)$, since a point kills every $I_\alpha$ iff it kills the ideal they generate. *Finite unions:* $V(I) \cup V(J) = V(I \cap J) = V(IJ)$. The inclusion $V(I) \cup V(J) \subseteq V(IJ)$ is clear since any element of $IJ$ is a sum of products $fg$ with $f \in I$, $g \in J$. Conversely if $x \notin V(I) \cup V(J)$, pick $f \in I$, $g \in J$ with $f(x) \neq 0 \neq g(x)$; then $fg \in IJ$ and $(fg)(x) \neq 0$, so $x \notin V(IJ)$. Closed sets thus include $\varnothing, k^n$ and are stable under arbitrary intersections and finite unions; complementing gives the open-set axioms. $\square$`,
  },
  {
    id: 'irreducible-variety',
    label: 'Irreducibility',
    title: 'Irreducible Variety',
    kind: 'definition',
    tags: ['Algebraic Geometry'],
    dependencies: ['affine-variety', 'zariski-topology', 'prime-ideal'],
    description: String.raw`The pair of lines $xy = 0$ is genuinely two pieces glued together; the parabola $y = x^2$ is a single piece. Irreducibility makes this precise: a variety is irreducible when it is not the union of two strictly smaller closed subsets. Under the algebra–geometry dictionary, irreducible corresponds to *prime*: the vanishing ideal of an irreducible variety is a prime ideal. Every algebraic set decomposes uniquely into finitely many maximal irreducible pieces, its irreducible components, so irreducible varieties are the indecomposable building blocks.`,
    definition: String.raw`A nonempty closed set $X$ (in the **Zariski topology**) is **irreducible** if it cannot be written as $X = X_1 \cup X_2$ with $X_1, X_2$ proper closed subsets of $X$ — equivalently, every nonempty open subset of $X$ is dense, equivalently any two nonempty open subsets meet. An **irreducible variety** is an irreducible affine (or projective) algebraic set.`,
    proof: String.raw`**$X = V(I)$ is irreducible iff its vanishing ideal $I(X)$ is a prime ideal.** Suppose $I(X)$ is **prime** and $X = X_1 \cup X_2$ with $X_i \subsetneq X$ closed. Pick $f \in I(X_1) \setminus I(X)$ and $g \in I(X_2) \setminus I(X)$ (possible as $X_i \neq X$). Then $fg$ vanishes on $X_1 \cup X_2 = X$, so $fg \in I(X)$; primeness forces $f \in I(X)$ or $g \in I(X)$, a contradiction. Hence $X$ is irreducible. Conversely, suppose $I(X)$ is not prime: either it is all of the ring (so $X = \varnothing$, excluded), or there are $f, g \notin I(X)$ with $fg \in I(X)$. Then $X = \bigl(X \cap V(f)\bigr) \cup \bigl(X \cap V(g)\bigr)$, since at every point of $X$ the product $fg$ vanishes so $f$ or $g$ does; and each piece is a *proper* closed subset (as $f, g$ do not vanish identically on $X$). Thus $X$ is reducible. $\square$`,
  },
  {
    id: 'coordinate-ring',
    label: 'Coordinate Ring',
    title: 'Coordinate Ring',
    kind: 'definition',
    tags: ['Algebraic Geometry'],
    dependencies: ['affine-variety', 'irreducible-variety', 'nullstellensatz', 'quotient-ring', 'prime-ideal', 'maximal-ideal'],
    description: String.raw`A polynomial function on a variety is a polynomial on the ambient $k^n$ restricted to the variety, but two polynomials that differ by something vanishing on the variety give the same function. Quotienting away the vanishing ideal packages all polynomial functions into a single ring, the coordinate ring. Over an algebraically closed field the Nullstellensatz makes the variety and its coordinate ring determine each other completely: points become maximal ideals, irreducible subvarieties become prime ideals, and closed subvarieties become radical ideals. Geometry has turned into commutative algebra.`,
    definition: String.raw`The **coordinate ring** of an affine variety $V \subseteq k^n$ is the **quotient ring**
$$k[V] := k[x_1, \dots, x_n]/I(V),$$
the ring of polynomial functions on $V$ (two polynomials being identified when they agree on $V$). It is a finitely generated $k$-algebra, and it is **reduced** (has no nonzero nilpotents) because $I(V)$ is a radical ideal.`,
    proof: String.raw`**Over an algebraically closed $k$, the points of $V$ correspond bijectively to the maximal ideals of $k[V]$, and irreducible closed subvarieties to its prime ideals.** Let $R = k[x_1, \dots, x_n]$. By the weak **Nullstellensatz** the maximal ideals of $R$ are exactly the $\mathfrak{m}_a = (x_1 - a_1, \dots, x_n - a_n)$ for $a \in k^n$, and $\mathfrak{m}_a \supseteq I(V)$ iff $a \in V$. The correspondence theorem for the **quotient ring** $k[V] = R/I(V)$ matches ideals of $k[V]$ with ideals of $R$ containing $I(V)$, preserving inclusions and hence maximality and primality. So maximal ideals of $k[V]$ correspond to maximal ideals $\mathfrak{m}_a \supseteq I(V)$, i.e. to points $a \in V$; and prime ideals of $k[V]$ correspond to primes of $R$ containing $I(V)$, which by **irreducible-variety** are the vanishing ideals of irreducible closed subvarieties of $V$. Finally $k[V]$ is reduced because, by the strong Nullstellensatz, $I(V) = I(V(I(V))) = \sqrt{I(V)}$ is radical, so it has no nilpotents in the quotient. $\square$`,
  },
  {
    id: 'morphism-of-varieties',
    label: 'Morphism of Varieties',
    title: 'Morphism of Varieties',
    kind: 'definition',
    tags: ['Algebraic Geometry'],
    dependencies: ['coordinate-ring', 'ring-homomorphism', 'nullstellensatz'],
    description: String.raw`The maps that respect algebraic structure are the ones given by polynomials, called regular maps or morphisms. Composing a polynomial function on the target with such a map yields a polynomial function on the source, so every morphism pulls functions back contravariantly, inducing a $k$-algebra homomorphism of coordinate rings. Over an algebraically closed field this pullback is a perfect dictionary: morphisms of affine varieties are exactly the $k$-algebra homomorphisms of their coordinate rings, run backwards. Geometric maps and algebra maps carry identical information.`,
    definition: String.raw`A **morphism** (regular map) of affine varieties $\varphi : V \to W$, with $V \subseteq k^n$ and $W \subseteq k^m$, is a map whose components are polynomials: $\varphi(x) = (f_1(x), \dots, f_m(x))$ with $f_i \in k[V]$ and $\varphi(V) \subseteq W$. It induces the **pullback**, a $k$-algebra **ring homomorphism**
$$\varphi^* : k[W] \to k[V], \qquad \varphi^*(g) = g \circ \varphi.$$`,
    proof: String.raw`**Over an algebraically closed field, $\varphi \mapsto \varphi^*$ is a bijection from morphisms $V \to W$ to $k$-algebra homomorphisms $k[W] \to k[V]$.** *Injectivity:* if $\varphi^* = \psi^*$ then $g \circ \varphi = g \circ \psi$ for all $g \in k[W]$; taking $g$ to be the coordinate functions $\bar{y}_j$ on $W$ gives $\varphi = \psi$. *Surjectivity:* given a $k$-algebra homomorphism $\Phi : k[W] \to k[V]$, set $f_j := \Phi(\bar{y}_j) \in k[V]$ and pick polynomial representatives, defining $\varphi = (f_1, \dots, f_m) : V \to k^m$. For any $h \in I(W)$ we have $h(\varphi(x)) = \Phi(\bar h)(x) = \Phi(0)(x) = 0$ for all $x \in V$ (using that $\bar h = 0$ in $k[W]$ and that $k$ is **algebraically closed**, so by the **Nullstellensatz** a polynomial function is zero iff it vanishes pointwise), whence $\varphi(V) \subseteq W$ and $\varphi^* = \Phi$. Thus $V \mapsto k[V]$ is a contravariant functor giving an anti-equivalence between affine varieties over $k$ and finitely generated reduced $k$-algebras. $\square$`,
  },
  {
    id: 'rational-map',
    label: 'Rational Map',
    title: 'Rational Map & Function Field',
    kind: 'definition',
    tags: ['Algebraic Geometry'],
    dependencies: ['morphism-of-varieties', 'irreducible-variety', 'localization'],
    description: String.raw`Allowing denominators enlarges morphisms to rational maps: maps given by ratios of polynomials, defined wherever a representative has nonzero denominator. On an irreducible variety the rational functions form a field, the function field, the fraction field of the coordinate ring. Two irreducible varieties are birational when their function fields are isomorphic over $k$ — equivalently when they become isomorphic after deleting lower-dimensional subsets. Birational equivalence is coarser than isomorphism, and classifying varieties up to it organizes much of the subject.`,
    definition: String.raw`Let $V$ be an irreducible affine variety, so $k[V]$ is an integral domain (its vanishing ideal is prime, by **irreducible-variety**). The **function field** $k(V)$ is the fraction field of $k[V]$, obtained by **localization** at the zero ideal; its elements are **rational functions** $g/h$ with $g, h \in k[V]$, $h \neq 0$, defined on the open set where $h \neq 0$. A **rational map** $\varphi : V \dashrightarrow W$ is a tuple of rational functions defined on a nonempty (hence dense) open subset of $V$ with image in $W$. $V$ and $W$ are **birational** if there are mutually inverse rational maps between them, equivalently if $k(V) \cong k(W)$ as extensions of $k$.`,
  },
  {
    id: 'dimension-of-a-variety',
    label: 'Dimension',
    title: 'Dimension of a Variety',
    kind: 'definition',
    tags: ['Algebraic Geometry'],
    dependencies: ['coordinate-ring', 'irreducible-variety', 'krull-dimension', 'rational-map'],
    description: String.raw`Dimension is the first and most basic invariant of a variety, and it agrees with geometric intuition: curves have dimension one, surfaces two, and affine $n$-space dimension $n$. It can be read off in three equivalent ways — geometrically as the length of the longest chain of nested irreducible subvarieties, algebraically as the Krull dimension of the coordinate ring, and for an irreducible variety as the transcendence degree of the function field over the base field. The agreement of these definitions is itself a substantial theorem of commutative algebra.`,
    definition: String.raw`The **dimension** of a variety $X$ is the supremum of lengths $d$ of chains of irreducible closed subvarieties
$$X_0 \subsetneq X_1 \subsetneq \cdots \subsetneq X_d \subseteq X.$$
Via the bijection of **irreducible-variety** (irreducible subvarieties $\leftrightarrow$ prime ideals), this equals the **Krull dimension** of the **coordinate ring** $k[X]$. For an irreducible $X$ it also equals the transcendence degree $\operatorname{trdeg}_k k(X)$ of the **function field** over $k$. Thus $\dim k^n = n$, curves have dimension $1$, surfaces dimension $2$.`,
  },
  {
    id: 'singular-point',
    label: 'Smooth & Singular Points',
    title: 'Smooth and Singular Points',
    kind: 'definition',
    tags: ['Algebraic Geometry'],
    dependencies: ['affine-variety', 'dimension-of-a-variety', 'jacobian', 'tangent-space'],
    description: String.raw`At a typical point a variety looks locally like affine space of its own dimension — it has a well-defined tangent space of the expected size. At a cusp, node, or self-crossing it does not, and the point is singular. The Jacobian criterion makes this computable: singular points are exactly where the matrix of partial derivatives of the defining equations drops rank, so the tangent space jumps in dimension. Resolution of singularities — replacing a variety by a smooth one birational to it — is a central theme, achieved by Hironaka in characteristic zero.`,
    definition: String.raw`Let $k$ be algebraically closed (or at least perfect) and let $X \subseteq k^n$ be a variety of dimension $d$ whose radical ideal of definition is $I(X) = (f_1, \dots, f_r)$, so that $X = V(I(X))$ is reduced. *(The Jacobian is computed from a specific generating set, so this hypothesis is essential: for the non-radical presentation $V(x^2) \subseteq k^1$ — the reduced point $x=0$, with $d=0$ — the matrix $J = (2x)$ gives $\operatorname{rank} J(0) = 0$ and would wrongly report a singularity, since $x^2$ does not generate the radical ideal $(x)$.)* The **Zariski tangent space** to $X$ at a point $p$ is the kernel of the **Jacobian** $J(p) = \bigl(\tfrac{\partial f_i}{\partial x_j}(p)\bigr)$, a linear **tangent-space** to $X$ at $p$; one always has $\dim_k \ker J(p) \ge d$. The point $p$ is **smooth** (nonsingular, regular) if equality holds, $\dim_k \ker J(p) = d$ — equivalently $\operatorname{rank} J(p) = n - d$, the maximal possible — and **singular** otherwise (where the rank drops, so the tangent space is strictly larger than $d$). A variety is **smooth** if every point is.`,
  },
  {
    id: 'intersection-multiplicity',
    label: 'Intersection Multiplicity',
    title: 'Intersection Multiplicity',
    kind: 'definition',
    tags: ['Algebraic Geometry'],
    dependencies: ['affine-variety', 'coordinate-ring', 'localization'],
    description: String.raw`Two curves can meet at a point in different ways — transversally, or tangentially, or with one of them singular there — and a robust count of intersections must weight each point by how the curves meet. The intersection multiplicity does this. A line meeting a parabola tangentially counts the contact point twice; a line through a node of a curve counts it with the multiplicity that makes the global count come out right. Algebraically the multiplicity at a point is the dimension, as a vector space over the field, of the local ring of the two curves at that point.`,
    definition: String.raw`Let $f, g \in k[x, y]$ define plane curves with no common component, and let $p$ be a point of $k^2$. The **intersection multiplicity** of the curves at $p$ is
$$I_p(f, g) := \dim_k \bigl(\mathcal{O}_{k^2, p} / (f, g)\bigr),$$
where $\mathcal{O}_{k^2, p}$ is the **local ring** at $p$ — the **localization** of $k[x, y]$ at the maximal ideal $\mathfrak{m}_p$, consisting of rational functions defined at $p$. Then $I_p(f, g) \ge 1$ exactly when $p$ lies on both curves, $I_p(f, g) = 1$ exactly when the curves are smooth at $p$ and meet transversally, and $I_p(f, g) < \infty$ since the curves share no component. The same construction with the **local ring** at $p$ defines intersection multiplicity for hypersurfaces and, with more care, for general subvarieties.`,
  },

  // ── Projective geometry ────────────────────────────────────────────────────
  {
    id: 'projective-space',
    label: 'Projective Space',
    title: 'Projective Space',
    kind: 'definition',
    tags: ['Algebraic Geometry'],
    dependencies: ['field', 'vector-space'],
    description: String.raw`Affine space is incomplete: parallel lines fail to meet, and a line and a conic may meet in fewer points than their degrees predict. Projective space repairs this by adjoining points at infinity, one for each direction. Concretely its points are the lines through the origin of a one-higher-dimensional vector space, equivalently the nonzero vectors up to scaling. The result compactifies affine space (over $\mathbb{R}$ or $\mathbb{C}$), makes parallel lines meet at a shared point at infinity, and makes intersection counts come out cleanly. It is the natural arena of the subject.`,
    definition: String.raw`Let $k$ be a field and $V = k^{n+1}$ a **vector space**. **Projective space** $\mathbb{P}^n(k)$ is the set of one-dimensional linear subspaces (lines through the origin) of $V$, equivalently the quotient
$$\mathbb{P}^n(k) = \bigl(k^{n+1} \setminus \{0\}\bigr)/\!\sim, \qquad (x_0, \dots, x_n) \sim (\lambda x_0, \dots, \lambda x_n)\ \ (\lambda \in k^\times).$$
The class of $(x_0, \dots, x_n)$ is written $[x_0 : \cdots : x_n]$ (**homogeneous coordinates**). The locus $x_0 \neq 0$ is a copy of affine space $k^n$ via $[1 : t_1 : \cdots : t_n]$, and its complement $x_0 = 0$ is a $\mathbb{P}^{n-1}$ of points at infinity.`,
  },
  {
    id: 'projective-variety',
    label: 'Projective Variety',
    title: 'Projective Variety',
    kind: 'definition',
    tags: ['Algebraic Geometry'],
    dependencies: ['affine-variety', 'projective-space', 'irreducible-variety'],
    description: String.raw`To cut out subsets of projective space one needs polynomials whose vanishing is independent of the choice of representative, and these are exactly the homogeneous polynomials: scaling the coordinates by $\lambda$ scales such a polynomial by a power of $\lambda$, so its zero set is well defined. Projective varieties enjoy completeness, the algebraic analogue of compactness, which is why intersection counts behave so well — over an algebraically closed field Bézout's theorem holds with no exceptions. Smooth projective curves are the geometric face of compact Riemann surfaces and a central object of number theory.`,
    definition: String.raw`A polynomial $f \in k[x_0, \dots, x_n]$ is **homogeneous** of degree $d$ if $f(\lambda x) = \lambda^d f(x)$; for such $f$ the condition $f(x) = 0$ is well defined on **projective space**. A **projective algebraic set** is the common zero locus in $\mathbb{P}^n$ of a family of homogeneous polynomials, and a **projective variety** is such a set (irreducible, under the convention of **irreducible-variety**). Intersecting with the affine chart $x_0 \neq 0$ recovers an **affine variety** (dehomogenization), and conversely an affine variety has a projective closure (homogenization).`,
  },
  {
    id: 'bezout-theorem',
    label: "Bézout's Theorem",
    title: "Bézout's Theorem",
    kind: 'theorem',
    tags: ['Algebraic Geometry'],
    dependencies: ['projective-variety', 'intersection-multiplicity', 'polynomial'],
    description: String.raw`In the projective plane over an algebraically closed field, two curves of degrees $m$ and $n$ with no common component meet in exactly $mn$ points, provided each intersection point is weighted by its multiplicity. Two lines meet once; a line and a conic twice; two conics four times. This exact count — valid only projectively (to capture intersections at infinity), only over an algebraically closed field (so roots exist), and only with multiplicities (so tangencies count correctly) — is the prototype of all intersection theory.`,
    statement: String.raw`Let $k$ be algebraically closed and let $C = V(f)$, $D = V(g)$ be plane projective curves in $\mathbb{P}^2(k)$, defined by homogeneous polynomials of degrees $m = \deg f$ and $n = \deg g$ with no common factor. Then
$$\sum_{p \in C \cap D} I_p(f, g) = mn,$$
the sum of the **intersection-multiplicity** taken over all (finitely many) common points.`,
    proof: String.raw`*A correct proof requires the theory of the resultant and of graded modules over $k[x_0, x_1, x_2]$, which lies beyond this graph; we give an honest sketch naming the two essential inputs.*

**Finiteness and the resultant.** Since $f, g$ are homogeneous with no common factor, the **polynomial** ring $k[x_0, x_1, x_2]$ being a UFD, they generate no common curve, so $C \cap D$ is finite. After a projective change of coordinates we may assume $[0:0:1] \notin C \cup D$; viewing $f, g$ as polynomials in $x_2$ with coefficients in $k[x_0, x_1]$, their **resultant** $\operatorname{Res}_{x_2}(f, g)$ is a homogeneous polynomial of degree exactly $mn$ in $x_0, x_1$. The resultant vanishes at $[x_0 : x_1]$ precisely when the two one-variable polynomials share a root, i.e. when $C$ and $D$ have a common point over that line; because $k$ is **algebraically closed**, this degree-$mn$ form has exactly $mn$ roots in $\mathbb{P}^1$ counted with multiplicity.

**Matching resultant multiplicity with intersection multiplicity.** The content of the theorem is that the order of vanishing of $\operatorname{Res}_{x_2}(f, g)$ at a point $[a_0 : a_1]$ equals the sum of the local **intersection-multiplicity** $I_p(f, g) = \dim_k(\mathcal{O}_{\mathbb{P}^2, p}/(f, g))$ over the points $p$ of $C \cap D$ lying above it. This local-to-global identity is the substantive step (proved via the structure of the finite $k$-algebra $\mathcal{O}_p/(f,g)$, or equivalently by computing the Hilbert polynomial of $k[x_0,x_1,x_2]/(f,g)$). Granting it, summing over all $mn$ roots of the resultant gives $\sum_{p \in C \cap D} I_p(f, g) = mn$.

The two cited inputs — the degree-$mn$ count of resultant roots, and the equality of resultant order with summed intersection multiplicity — are exactly the gap relative to the present graph. $\square$`,
  },

  // ── Sheaves, schemes, and a featured curve ─────────────────────────────────
  {
    id: 'sheaf',
    label: 'Sheaf',
    title: 'Sheaf',
    kind: 'definition',
    tags: ['Algebraic Geometry'],
    dependencies: ['topological-space', 'category', 'functor'],
    description: String.raw`Much of geometry is about passing between local and global data — local solutions, local functions, local sections — and gluing them when they agree. A sheaf is the bookkeeping device for exactly this. It assigns to each open set a set (or ring, or module) of "sections," with restriction maps to smaller opens, subject to two gluing axioms: sections agreeing on overlaps are determined by their local pieces, and compatible local sections always glue to a global one. The structure sheaf of regular functions turns a variety into a ringed space and is the bridge from varieties to schemes.`,
    definition: String.raw`A **presheaf** $\mathcal{F}$ (of sets, say) on a **topological space** $X$ assigns to each open $U \subseteq X$ a set $\mathcal{F}(U)$ and to each inclusion $V \subseteq U$ a **restriction** map $\rho^U_V : \mathcal{F}(U) \to \mathcal{F}(V)$, with $\rho^U_U = \mathrm{id}$ and $\rho^U_W = \rho^V_W \circ \rho^U_V$ (a contravariant functor from the open sets, ordered by inclusion as a **category**, to sets). A **sheaf** is a presheaf satisfying, for every open cover $U = \bigcup_i U_i$: **(identity)** if $s, t \in \mathcal{F}(U)$ have $s|_{U_i} = t|_{U_i}$ for all $i$, then $s = t$; and **(gluing)** if sections $s_i \in \mathcal{F}(U_i)$ agree on overlaps, $s_i|_{U_i \cap U_j} = s_j|_{U_i \cap U_j}$, then there is a (unique, by identity) $s \in \mathcal{F}(U)$ with $s|_{U_i} = s_i$.`,
  },
  {
    id: 'scheme',
    label: 'Scheme',
    title: 'Scheme',
    kind: 'definition',
    tags: ['Algebraic Geometry'],
    dependencies: ['spectrum-of-a-ring', 'sheaf', 'morphism-of-varieties', 'ring-homomorphism', 'localization'],
    description: String.raw`Grothendieck's schemes are the sweeping generalization that gave the subject its modern foundations. The starting point is that any commutative ring already is a geometric object: its spectrum is a topological space carrying a structure sheaf of "functions." A scheme is anything locally modeled on such a spectrum, glued together. Allowing arbitrary rings — with nilpotents (which remember infinitesimal thickening), over any base, including $\mathbb{Z}$ — schemes unify classical algebraic geometry with number theory, so that a Diophantine equation and a complex variety are objects of the same kind.`,
    definition: String.raw`An **affine scheme** is the pair $(\operatorname{Spec} R, \mathcal{O}_{\operatorname{Spec} R})$ where the underlying space is the **spectrum** of a commutative ring $R$ with its Zariski topology, and $\mathcal{O}$ is its **structure sheaf**, the sheaf of rings whose sections over the basic open $D(f) = \{\mathfrak{p} : f \notin \mathfrak{p}\}$ are the localization $R_f$ (so the stalk at $\mathfrak{p}$ is the local ring $R_\mathfrak{p}$). A **scheme** is a ringed space $(X, \mathcal{O}_X)$ that is locally isomorphic to an affine scheme: $X$ has an open cover by sets $U_i$ with $(U_i, \mathcal{O}_X|_{U_i}) \cong (\operatorname{Spec} R_i, \mathcal{O}_{\operatorname{Spec} R_i})$. **Morphisms** of schemes are maps of ringed spaces that are locally, on affine pieces, induced by **ring homomorphisms** (generalizing the affine-variety pullback of **morphism-of-varieties**); an affine variety over an algebraically closed field is the scheme $\operatorname{Spec} k[V]$.`,
  },
  {
    id: 'elliptic-curve',
    label: 'Elliptic Curve',
    title: 'Elliptic Curve',
    kind: 'definition',
    tags: ['Algebraic Geometry'],
    dependencies: ['projective-variety', 'singular-point', 'group', 'bezout-theorem'],
    description: String.raw`An elliptic curve is a smooth projective curve of genus one equipped with a chosen base point. Over a field of characteristic not $2$ or $3$ it can be put in Weierstrass form $y^2 = x^3 + ax + b$ with the cubic on the right having distinct roots — the smoothness condition. Its defining feature is a group law: three points sum to zero exactly when they are collinear, which turns the chord-and-tangent construction into abelian addition with the base point as identity. This places elliptic curves at the crossroads of geometry, number theory (Fermat's Last Theorem, Birch–Swinnerton-Dyer), and cryptography.`,
    definition: String.raw`Over a field $k$ of characteristic $\neq 2, 3$, an **elliptic curve** is the projective plane curve $E \subseteq \mathbb{P}^2(k)$ given by a **Weierstrass equation** (in homogeneous form $Y^2 Z = X^3 + aXZ^2 + bZ^3$, affinely $y^2 = x^3 + ax + b$) with nonzero **discriminant** $\Delta = -16(4a^3 + 27b^2) \neq 0$, together with the chosen base point $O = [0 : 1 : 0]$ at infinity. The condition $\Delta \neq 0$ says the cubic has distinct roots, equivalently $E$ has no **singular-point**; such an $E$ is a smooth **projective variety** of genus one. Its points carry an abelian **group** law with identity $O$, characterized by: $P + Q + R = O$ whenever $P, Q, R$ are collinear in $\mathbb{P}^2$.`,
    proof: String.raw`**The chord-and-tangent law makes $E$ an abelian group with identity $O$.** Define $P + Q$ as follows: the line through $P$ and $Q$ (the tangent at $P$ if $P = Q$) meets the cubic $E$ in a unique third point $R$ (it meets in exactly three points with multiplicity by **Bézout's theorem**, a line and a cubic having degrees $1$ and $3$, and $k$ being where roots lie); then $P + Q$ is the third intersection of the line through $R$ and $O$ with $E$. *Identity:* the line $OP$ meets $E$ at $O, P$ and a third point $R$, and the line $RO$ then returns $P$, so $O + P = P$. *Inverses:* $-P$ is the third point on the line through $P$ and $O$. *Commutativity* is immediate as the line through $P, Q$ does not depend on order. *Associativity* is the only nontrivial axiom; it follows from the collinearity characterization via the Cayley–Bacharach property of cubics (two cubics through eight common points of a pencil share the ninth), or intrinsically from the identification of $E$ with its degree-zero divisor class group $\operatorname{Pic}^0(E)$ through $P \mapsto [P] - [O]$ — a result that needs the Riemann–Roch theorem, named here as the input beyond this graph. Granting associativity, $(E, +)$ is an abelian **group**. $\square$`,
  },
]
