import type { MathNode } from '../types'

export const ALGEBRAIC_NUMBER_THEORY_NODES: MathNode[] = [
  // ── Algebraic integers and number fields ───────────────────────────────────
  {
    id: 'algebraic-integer',
    label: 'Algebraic Integer',
    title: 'Algebraic Integer',
    kind: 'definition',
    tags: ['Algebraic Number Theory'],
    dependencies: ['polynomial', 'integers', 'rationals', 'integral-element', 'complex-numbers'],
    description: String.raw`Among all algebraic numbers, some deserve to be called *integers*: those that satisfy a polynomial equation whose leading coefficient is $1$ and whose other coefficients are ordinary integers. The numbers $\sqrt{2}$, $i$, and the roots of unity qualify; $\tfrac{1}{2}$ does not, because no monic integer polynomial has it as a root. This is the special case $R = \mathbb{Z}$, $S = \mathbb{C}$ of the general notion of an integral element, and it singles out exactly the algebraic numbers whose arithmetic mirrors that of $\mathbb{Z}$ — the basic objects whose factorization, primes, and units number theory studies.`,
    definition: String.raw`An **algebraic integer** is a complex number $\alpha$ that is **integral over $\mathbb{Z}$**: it satisfies a **monic** polynomial relation
$$\alpha^n + c_{n-1}\alpha^{n-1} + \cdots + c_1\alpha + c_0 = 0, \qquad c_i \in \mathbb{Z}.$$
Equivalently, $\alpha$ is an algebraic integer iff its **minimal polynomial** over $\mathbb{Q}$ lies in $\mathbb{Z}[x]$ (and is monic). The rational algebraic integers are exactly the ordinary integers: $\mathbb{Q} \cap \{\text{algebraic integers}\} = \mathbb{Z}$.`,
  },
  {
    id: 'algebraic-integers-ring',
    label: 'Algebraic Integers Form a Ring',
    title: 'The Algebraic Integers Form a Ring',
    kind: 'proposition',
    tags: ['Algebraic Number Theory'],
    dependencies: ['algebraic-integer', 'integral-element', 'ring', 'noetherian-ring'],
    description: String.raw`It is not obvious from the definition that sums and products of algebraic integers are again algebraic integers — adding two roots of monic integer polynomials does not obviously give a root of a third. The resolution is the module-finiteness characterization of integrality: $\alpha$ is integral over $\mathbb{Z}$ exactly when $\mathbb{Z}[\alpha]$ is a finitely generated $\mathbb{Z}$-module, and finite generation is preserved under the operations of the ring. This makes the algebraic integers a subring of $\mathbb{C}$, the ambient ring inside which every ring of integers of a number field sits.`,
    statement: String.raw`The set $\overline{\mathbb{Z}}$ of all algebraic integers is a subring of $\mathbb{C}$: it contains $0$ and $1$ and is closed under subtraction and multiplication.`,
    proof: String.raw`This is the special case $R = \mathbb{Z} \subseteq S = \mathbb{C}$ of the general theorem that the **integral elements** of a ring extension form a subring (the integral closure). We recall the mechanism. By the module-finiteness criterion recorded in **integral-element**, $\alpha$ is integral over $\mathbb{Z}$ iff $\mathbb{Z}[\alpha]$ is a finitely generated $\mathbb{Z}$-module — if $\alpha$ satisfies a monic relation of degree $n$, then $1, \alpha, \dots, \alpha^{n-1}$ generate $\mathbb{Z}[\alpha]$.

Let $\alpha, \beta$ be algebraic integers, say with $\mathbb{Z}[\alpha]$ generated by $m$ elements and $\mathbb{Z}[\beta]$ by $k$ elements. Then $\mathbb{Z}[\alpha, \beta]$ is generated as a $\mathbb{Z}$-module by the $mk$ products $\alpha^i\beta^j$, hence is finitely generated. The subring $\mathbb{Z}[\alpha \pm \beta]$ and $\mathbb{Z}[\alpha\beta]$ sit inside the finitely generated $\mathbb{Z}$-module $\mathbb{Z}[\alpha,\beta]$, and a submodule of a finitely generated module over the Noetherian ring $\mathbb{Z}$ is again finitely generated; so $\mathbb{Z}[\alpha \pm \beta]$ and $\mathbb{Z}[\alpha\beta]$ are finitely generated $\mathbb{Z}$-modules. By the criterion in the reverse direction, $\alpha \pm \beta$ and $\alpha\beta$ are integral over $\mathbb{Z}$, i.e. algebraic integers. Since $0, 1 \in \mathbb{Z} \subseteq \overline{\mathbb{Z}}$, the set $\overline{\mathbb{Z}}$ is a **ring**. $\square$`,
  },
  {
    id: 'number-field',
    label: 'Number Field',
    title: 'Number Field',
    kind: 'definition',
    tags: ['Algebraic Number Theory'],
    dependencies: ['field-extension', 'rationals'],
    description: String.raw`The natural arenas of algebraic number theory are the fields obtained by adjoining finitely many algebraic numbers to $\mathbb{Q}$ — for instance $\mathbb{Q}(\sqrt{2})$, $\mathbb{Q}(i)$, or $\mathbb{Q}(\sqrt[3]{2})$. Each is finite-dimensional as a vector space over $\mathbb{Q}$, and that dimension, the degree, controls everything: the number of embeddings into $\mathbb{C}$, the rank of the unit group, and how primes can split. By the primitive element theorem every such field is $\mathbb{Q}(\theta)$ for a single algebraic number $\theta$, so a number field is just $\mathbb{Q}[x]/(f)$ for an irreducible $f$.`,
    definition: String.raw`A **number field** is a **field extension** $K/\mathbb{Q}$ of finite degree: a field $K \supseteq \mathbb{Q}$ that is finite-dimensional as a $\mathbb{Q}$-vector space. Its **degree** is $n = [K : \mathbb{Q}] = \dim_{\mathbb{Q}} K$. Every element of $K$ is algebraic over $\mathbb{Q}$, and (by the primitive element theorem for the separable extension $K/\mathbb{Q}$) $K = \mathbb{Q}(\theta)$ for some $\theta$, so $K \cong \mathbb{Q}[x]/(f)$ with $f$ the minimal polynomial of $\theta$, of degree $n$.`,
  },
  {
    id: 'field-norm-trace',
    label: 'Norm & Trace',
    title: 'Field Norm and Trace',
    kind: 'definition',
    tags: ['Algebraic Number Theory'],
    dependencies: ['number-field', 'linear-map', 'determinant'],
    description: String.raw`To do arithmetic in a number field $K$ one needs scalar-valued measurements of its elements that land back in $\mathbb{Q}$. Multiplication by a fixed element $\alpha$ is a $\mathbb{Q}$-linear map of $K$ to itself; its determinant and trace are the **norm** and **trace** of $\alpha$. The norm is multiplicative and the trace additive, and both restrict the size of an element. They are the engines behind the discriminant, behind the proof that ideal norms are multiplicative, and behind the geometry-of-numbers arguments; for $\mathbb{Q}(\sqrt{d})$ they recover $N(a + b\sqrt{d}) = a^2 - db^2$ and $\operatorname{Tr}(a + b\sqrt{d}) = 2a$.`,
    definition: String.raw`Let $K/\mathbb{Q}$ be a number field of degree $n$ and $\alpha \in K$. Multiplication by $\alpha$, $m_\alpha : K \to K$, $x \mapsto \alpha x$, is a $\mathbb{Q}$-**linear map** of the $n$-dimensional $\mathbb{Q}$-vector space $K$. The **norm** and **trace** of $\alpha$ are
$$N_{K/\mathbb{Q}}(\alpha) = \det(m_\alpha), \qquad \operatorname{Tr}_{K/\mathbb{Q}}(\alpha) = \operatorname{tr}(m_\alpha),$$
the **determinant** and **trace** of this map; both lie in $\mathbb{Q}$. Equivalently, if $\sigma_1, \dots, \sigma_n : K \hookrightarrow \mathbb{C}$ are the $n$ distinct embeddings of $K$, then $N_{K/\mathbb{Q}}(\alpha) = \prod_i \sigma_i(\alpha)$ and $\operatorname{Tr}_{K/\mathbb{Q}}(\alpha) = \sum_i \sigma_i(\alpha)$. The norm is multiplicative, $N(\alpha\beta) = N(\alpha)N(\beta)$, and the trace is $\mathbb{Q}$-linear; for an algebraic integer both are ordinary integers.`,
  },
  {
    id: 'ring-of-integers',
    label: 'Ring of Integers',
    title: 'Ring of Integers',
    kind: 'definition',
    tags: ['Algebraic Number Theory'],
    dependencies: ['number-field', 'algebraic-integer', 'algebraic-integers-ring', 'dedekind-domain', 'field-norm-trace', 'integral-element'],
    description: String.raw`Inside each number field $K$ sits a distinguished subring: the algebraic integers that happen to lie in $K$. It plays the role $\mathbb{Z}$ plays inside $\mathbb{Q}$ — for $\mathbb{Q}(i)$ it is the Gaussian integers $\mathbb{Z}[i]$, for $\mathbb{Q}(\sqrt{-5})$ it is $\mathbb{Z}[\sqrt{-5}]$. It is a free $\mathbb{Z}$-module of rank $[K:\mathbb{Q}]$, so it has an integral basis, and crucially it is always a Dedekind domain. It need not be a unique factorization domain — that failure is precisely what the class group measures — but the Dedekind property restores unique factorization at the level of ideals.`,
    definition: String.raw`The **ring of integers** of a number field $K$ is
$$\mathcal{O}_K = \{\alpha \in K : \alpha \text{ is an } \textbf{algebraic integer}\} = \overline{\mathbb{Z}} \cap K,$$
the integral closure of $\mathbb{Z}$ in $K$. It is a subring of $K$ (intersection of the ring $\overline{\mathbb{Z}}$ of all algebraic integers with the field $K$) with fraction field $K$, free of rank $n = [K:\mathbb{Q}]$ as a $\mathbb{Z}$-module (an **integral basis**), and a **Dedekind domain**: Noetherian, integrally closed in $K$, of Krull dimension one.`,
    proof: String.raw`*Why $\mathcal{O}_K$ is well-defined and a Dedekind domain.* That $\mathcal{O}_K$ is a ring is immediate: it is the intersection of the ring $\overline{\mathbb{Z}}$ of all algebraic integers (a ring by **algebraic-integers-ring**) with the field $K$. We verify the three **Dedekind-domain** axioms. *Integrally closed:* if $\beta \in K$ is integral over $\mathcal{O}_K$, then by transitivity of integrality $\beta$ is integral over $\mathbb{Z}$, so $\beta \in \overline{\mathbb{Z}} \cap K = \mathcal{O}_K$; thus $\mathcal{O}_K$ equals its own integral closure in its fraction field $K$. *Noetherian and a free $\mathbb{Z}$-module of rank $n$:* using the nondegeneracy of the trace pairing $(\alpha,\beta) \mapsto \operatorname{Tr}_{K/\mathbb{Q}}(\alpha\beta)$ for the separable extension $K/\mathbb{Q}$, one sandwiches $\mathcal{O}_K$ between two free $\mathbb{Z}$-modules of rank $n$, $M \subseteq \mathcal{O}_K \subseteq M^{\#}$ (the dual lattice of an integral-basis-candidate $M$); a submodule of a finitely generated module over the Noetherian ring $\mathbb{Z}$ is finitely generated, so $\mathcal{O}_K$ is a finitely generated, torsion-free, hence free $\mathbb{Z}$-module of rank $n$, and a fortiori a Noetherian ring. *Dimension one:* every nonzero prime $\mathfrak{p}$ contains a nonzero rational integer $m$ (e.g. $N_{K/\mathbb{Q}}$ of a nonzero element of $\mathfrak{p}$), so $\mathcal{O}_K/\mathfrak{p}$ is a finite ring that is a domain, hence a field, so $\mathfrak{p}$ is maximal. All three axioms hold, so $\mathcal{O}_K$ is a Dedekind domain. $\square$`,
  },
  {
    id: 'embeddings-number-field',
    label: 'Real & Complex Embeddings',
    title: 'Embeddings and Signature of a Number Field',
    kind: 'definition',
    tags: ['Algebraic Number Theory'],
    dependencies: ['number-field', 'complex-numbers', 'field-norm-trace'],
    description: String.raw`A number field of degree $n$ has exactly $n$ distinct ways to be embedded into $\mathbb{C}$, the roots of a defining polynomial $f$ supplying the images of a primitive element. These embeddings come in two flavors: those landing in $\mathbb{R}$ (real embeddings) and those landing genuinely in $\mathbb{C}$, which occur in complex-conjugate pairs. The count $(r_1, r_2)$ of real embeddings and conjugate pairs — the **signature** — is the single combinatorial invariant governing the unit rank in Dirichlet's theorem and the shape of the Minkowski embedding used in the geometry of numbers.`,
    definition: String.raw`Let $K = \mathbb{Q}(\theta)$ be a number field of degree $n$, with $\theta$ having minimal polynomial $f \in \mathbb{Q}[x]$. The **embeddings** of $K$ are the $n$ field homomorphisms $\sigma : K \hookrightarrow \mathbb{C}$ (each $\mathbb{Q}$-linear and sending $\theta$ to one of the $n$ distinct roots of $f$). An embedding is **real** if $\sigma(K) \subseteq \mathbb{R}$ and **complex** otherwise; complex embeddings occur in conjugate pairs $\sigma, \bar\sigma$. Writing $r_1$ for the number of real embeddings and $r_2$ for the number of conjugate pairs of complex embeddings, the **signature** is $(r_1, r_2)$ and
$$r_1 + 2 r_2 = n.$$
The **Minkowski embedding** $K \hookrightarrow \mathbb{R}^{r_1} \times \mathbb{C}^{r_2} \cong \mathbb{R}^n$, $\alpha \mapsto (\sigma_1(\alpha), \dots, \sigma_{r_1}(\alpha), \sigma_{r_1+1}(\alpha), \dots, \sigma_{r_1+r_2}(\alpha))$ (one $\sigma$ per conjugate pair), is the map used in the geometry of numbers; under it $\mathcal{O}_K$ becomes a full lattice in $\mathbb{R}^n$. The full **norm and trace** are recovered from all $n$ embeddings, $\operatorname{Tr}_{K/\mathbb{Q}}(\alpha) = \sum_{j=1}^{n} \sigma_j(\alpha)$ and $N_{K/\mathbb{Q}}(\alpha) = \prod_{j=1}^{n} \sigma_j(\alpha)$, counting both members of each complex pair; in terms of the chosen representatives, $\operatorname{Tr}_{K/\mathbb{Q}}(\alpha) = \sum_{j=1}^{r_1}\sigma_j(\alpha) + \sum_{k=1}^{r_2} 2\operatorname{Re}\,\sigma_{r_1+k}(\alpha)$.`,
  },
  {
    id: 'discriminant',
    label: 'Discriminant',
    title: 'Discriminant of a Number Field',
    kind: 'definition',
    tags: ['Algebraic Number Theory'],
    dependencies: ['ring-of-integers', 'field-norm-trace'],
    description: String.raw`The discriminant is a single integer attached to a number field that packages how its ring of integers sits geometrically and where its arithmetic is special. It is computed from the trace pairing on an integral basis, and its value answers a sharp question: a rational prime ramifies in $K$ exactly when it divides the discriminant — so the finitely many "bad" primes are read off this one number. Its absolute value also measures the covolume of $\mathcal{O}_K$ under the Minkowski embedding, linking it to the geometry of numbers; by Minkowski's theorem only $\mathbb{Q}$ itself has discriminant $\pm 1$.`,
    definition: String.raw`Let $K$ be a number field of degree $n$ with integral basis $\omega_1, \dots, \omega_n$ of $\mathcal{O}_K$. The **discriminant** of $K$ is
$$d_K = \det\bigl(\operatorname{Tr}_{K/\mathbb{Q}}(\omega_i\omega_j)\bigr)_{i,j=1}^{n} = \det(\sigma_i(\omega_j))^2,$$
the determinant of the trace-form Gram matrix (using the **norm and trace**), equivalently the square of the determinant of the matrix of embeddings $\sigma_i(\omega_j)$. It is a nonzero integer, independent of the chosen integral basis (a change of basis multiplies the embedding matrix by a matrix in $\mathrm{GL}_n(\mathbb{Z})$, of determinant $\pm 1$, so $d_K$ is unchanged). A rational prime $p$ **ramifies** in $K$ iff $p \mid d_K$, and under the Minkowski embedding $\mathcal{O}_K$ is a full lattice of covolume $2^{-r_2}\sqrt{|d_K|}$ (so its squared covolume is $2^{-2r_2}|d_K|$), where $r_2$ is the number of complex places.`,
  },

  // ── Ideal theory ───────────────────────────────────────────────────────────
  {
    id: 'ideal-factorization',
    label: 'Ideal Factorization',
    title: 'Unique Factorization of Ideals',
    kind: 'theorem',
    tags: ['Algebraic Number Theory'],
    dependencies: ['ring-of-integers', 'dedekind-domain', 'prime-ideal'],
    description: String.raw`The historical crisis of algebraic number theory was that elements of $\mathcal{O}_K$ can factor non-uniquely: in $\mathbb{Z}[\sqrt{-5}]$ one has $6 = 2\cdot 3 = (1+\sqrt{-5})(1-\sqrt{-5})$, two genuinely different factorizations into irreducibles. Kummer and Dedekind's resolution was to replace numbers by ideals: although elements misbehave, every nonzero ideal of $\mathcal{O}_K$ factors uniquely into prime ideals. Unique factorization is not lost, merely relocated from elements to ideals — and this is exactly the defining property of a Dedekind domain, which $\mathcal{O}_K$ always is.`,
    statement: String.raw`Let $K$ be a number field. Every nonzero proper ideal $I \subseteq \mathcal{O}_K$ factors as a product of nonzero **prime ideals**,
$$I = \mathfrak{p}_1^{a_1}\mathfrak{p}_2^{a_2}\cdots\mathfrak{p}_g^{a_g} \qquad (a_i \ge 1),$$
and this factorization is unique up to the order of the factors.`,
    proof: String.raw`By **ring-of-integers**, $\mathcal{O}_K$ is a **Dedekind domain**. The equivalent characterization of a Dedekind domain established in **dedekind-domain** is precisely that a domain (not a field) is Dedekind *iff* every nonzero proper ideal factors uniquely into prime ideals. We recall the mechanism for completeness. The crux is that in a Dedekind domain every nonzero ideal $I$ is **invertible**: with $I^{-1} = \{x \in K : xI \subseteq \mathcal{O}_K\}$ in the fraction field $K$, one has $I I^{-1} = \mathcal{O}_K$ — proved using the Noetherian property (so $I$ contains a product of nonzero primes), dimension one (so nonzero primes are maximal), and integral closedness (to force $\mathfrak{p}^{-1} \supsetneq \mathcal{O}_K$ for a maximal $\mathfrak{p}$). Granting invertibility, *existence* follows by Noetherian induction: pick a maximal ideal $\mathfrak{p} \supseteq I$; then $\mathfrak{p}^{-1}I$ is an ideal strictly containing $I$, whose factorization (induction) times $\mathfrak{p}$ gives one for $I$. *Uniqueness*: if $\mathfrak{p}_1\cdots\mathfrak{p}_r = \mathfrak{q}_1\cdots\mathfrak{q}_s$, then $\mathfrak{p}_1$ contains the right side, so by the **prime-ideal** property contains some $\mathfrak{q}_j$, and maximality gives $\mathfrak{p}_1 = \mathfrak{q}_j$; cancel the invertible factor $\mathfrak{p}_1$ and induct. $\square$`,
  },
  {
    id: 'ideal-norm',
    label: 'Norm of an Ideal',
    title: 'Norm of an Ideal',
    kind: 'definition',
    tags: ['Algebraic Number Theory'],
    dependencies: ['ideal-factorization', 'field-norm-trace'],
    description: String.raw`Just as an element has a norm, so does an ideal, and the two agree on principal ideals. The norm of an ideal is simply the number of elements in the quotient ring $\mathcal{O}_K/I$ — always finite — and it is multiplicative across the prime factorization. This makes the norm a homomorphism from ideals to positive integers, the tool that converts statements about ideals into statements about sizes; it is what makes "only finitely many ideals of bounded norm" true, and hence what powers the finiteness of the class number.`,
    definition: String.raw`The **norm** of a nonzero ideal $I \subseteq \mathcal{O}_K$ is the (finite) cardinality of the quotient ring,
$$N(I) = |\mathcal{O}_K / I| \in \mathbb{Z}_{\ge 1}.$$
It is **multiplicative**: $N(IJ) = N(I)N(J)$, which by **ideal-factorization** reduces computation to the prime powers $N(\mathfrak{p}^a) = N(\mathfrak{p})^a$. For a principal ideal it agrees with the element norm up to sign, $N((\alpha)) = |N_{K/\mathbb{Q}}(\alpha)|$ (the **field norm and trace**), and only finitely many ideals have a given norm, since each contains the integer $N(I)$ and $\mathcal{O}_K/(N(I))$ is finite.`,
  },
  {
    id: 'ramification',
    label: 'Ramification',
    title: 'Ramification of Primes',
    kind: 'definition',
    tags: ['Algebraic Number Theory'],
    dependencies: ['ideal-factorization', 'ideal-norm', 'discriminant'],
    description: String.raw`A rational prime $p$, once pushed into $\mathcal{O}_K$, need not stay prime: the ideal $p\,\mathcal{O}_K$ factors. How it factors is the central local question of the subject. The exponents in the factorization are the ramification indices and the degrees of the residue fields are the residue degrees; they are linked by a clean conservation law summing to $[K:\mathbb{Q}]$. A prime is unramified when no exponent exceeds $1$ — the generic case — and ramified otherwise; the ramified primes are finite in number and are exactly those dividing the discriminant, marking where the field's arithmetic is intricate.`,
    definition: String.raw`Let $K/\mathbb{Q}$ have degree $n$ and let $p$ be a rational prime. In $\mathcal{O}_K$ the ideal $p\,\mathcal{O}_K$ factors (by **ideal-factorization**) as
$$p\,\mathcal{O}_K = \mathfrak{p}_1^{e_1}\cdots\mathfrak{p}_g^{e_g},$$
with the $\mathfrak{p}_i$ distinct primes above $p$. The exponent $e_i$ is the **ramification index** and $f_i = [\mathcal{O}_K/\mathfrak{p}_i : \mathbb{F}_p]$ (so $N(\mathfrak{p}_i) = p^{f_i}$, the **ideal norm**) is the **residue degree**; they satisfy the fundamental identity
$$\sum_{i=1}^{g} e_i f_i = n.$$
The prime $p$ is **unramified** if every $e_i = 1$ and **ramifies** if some $e_i > 1$; among unramified primes it **splits** if $g > 1$ and is **inert** if $g = 1, f_1 = n$ (i.e. $p\,\mathcal{O}_K$ stays prime). The ramified primes are precisely those dividing the **discriminant** $d_K$, hence finitely many.`,
  },

  // ── Class group and units ──────────────────────────────────────────────────
  {
    id: 'ideal-class-group',
    label: 'Ideal Class Group',
    title: 'Ideal Class Group',
    kind: 'definition',
    tags: ['Algebraic Number Theory'],
    dependencies: ['ideal-factorization', 'principal-ideal-domain', 'unique-factorization-domain', 'dedekind-domain'],
    description: String.raw`Although ideals of $\mathcal{O}_K$ factor uniquely, the ring may still fail to be a unique factorization domain — and the obstruction is measured by a finite abelian group, the ideal class group. One forms the group of all nonzero fractional ideals under multiplication and collapses the principal ones to the identity; what remains records exactly how far $\mathcal{O}_K$ is from being a principal ideal domain. The group is trivial precisely when $\mathcal{O}_K$ is a PID (equivalently a UFD), and its order, the class number, is the single most important measure of the field's arithmetic complexity.`,
    definition: String.raw`A **fractional ideal** of $\mathcal{O}_K$ is a nonzero finitely generated $\mathcal{O}_K$-submodule of $K$ (equivalently $\tfrac{1}{d}I$ for an ideal $I$ and $0 \neq d \in \mathcal{O}_K$). Under multiplication the fractional ideals form an abelian **group** $\mathcal{I}_K$ (each is invertible, as in **ideal-factorization**), freely generated by the prime ideals. The nonzero **principal** fractional ideals $(\alpha) = \alpha\mathcal{O}_K$ form a subgroup $\mathcal{P}_K$, and the **ideal class group** is the quotient
$$\mathrm{Cl}(K) = \mathcal{I}_K / \mathcal{P}_K.$$
Its order $h_K = |\mathrm{Cl}(K)|$ is the **class number**. Then $\mathrm{Cl}(K)$ is trivial ($h_K = 1$) iff every ideal is principal, i.e. iff $\mathcal{O}_K$ is a **principal ideal domain** — equivalently (since a Dedekind PID is a UFD and a Dedekind **unique factorization domain** is a PID) iff $\mathcal{O}_K$ is a UFD.`,
  },
  {
    id: 'minkowski-bound',
    label: 'Minkowski Bound',
    title: 'Minkowski Bound',
    kind: 'theorem',
    tags: ['Algebraic Number Theory'],
    dependencies: ['ideal-norm', 'embeddings-number-field', 'discriminant'],
    description: String.raw`The geometry of numbers turns counting ideals into counting lattice points in a convex region. Embedding $\mathcal{O}_K$ into $\mathbb{R}^n$ via its real and complex embeddings makes it a full lattice whose covolume is governed by the discriminant; Minkowski's lattice-point theorem then forces any symmetric convex body of large enough volume to contain a nonzero lattice point. Applied to a suitable box, this produces, in every ideal class, an integral ideal whose norm is bounded by an explicit constant depending only on the degree, signature, and discriminant — the indispensable effective input for both finiteness of the class number and its computation.`,
    statement: String.raw`Let $K$ be a number field of degree $n = r_1 + 2 r_2$ (signature $(r_1, r_2)$) and discriminant $d_K$. Every ideal class of $\mathrm{Cl}(K)$ contains an integral ideal $\mathfrak{a}$ with
$$N(\mathfrak{a}) \le M_K := \Bigl(\frac{4}{\pi}\Bigr)^{\!r_2} \frac{n!}{n^n}\sqrt{|d_K|}.$$
The constant $M_K$ is the **Minkowski bound**.`,
    proof: String.raw`*Sketch via the geometry of numbers, naming the deep input.* Under the **Minkowski embedding** $\iota : K \to \mathbb{R}^{r_1}\times\mathbb{C}^{r_2} \cong \mathbb{R}^n$ of **embeddings-number-field**, $\mathcal{O}_K$ maps to a full lattice $\Lambda$ whose fundamental covolume is $2^{-r_2}\sqrt{|d_K|}$ (the squared covolume is $2^{-2r_2}|d_K|$ by **discriminant**); more generally a nonzero ideal $\mathfrak{b}$ maps to a lattice of covolume $2^{-r_2}N(\mathfrak{b})\sqrt{|d_K|}$ (using the **ideal-norm** $N(\mathfrak{b}) = [\mathcal{O}_K : \mathfrak{b}]$).

The key external theorem is **Minkowski's convex body theorem** (a result of the geometry of numbers, not formalized elsewhere in this graph): a convex, centrally symmetric region of volume $> 2^n \operatorname{covol}(\Lambda)$ contains a nonzero point of $\Lambda$. Applying it to the region $\{(y_i, z_j) : \sum |y_i| + 2\sum |z_j| \le t\}$ — convex and symmetric, of volume $2^{r_1}(\pi/2)^{r_2} t^n/n!$ — with $t$ chosen just large enough relative to the covolume of $\iota(\mathfrak{b})$ produces a nonzero $\alpha \in \mathfrak{b}$ with $|N_{K/\mathbb{Q}}(\alpha)| \le (4/\pi)^{r_2}(n!/n^n)\sqrt{|d_K|}\,N(\mathfrak{b})$, by the AM–GM inequality bounding the norm by the linear constraint.

Now fix an ideal class $C$. Choose an integral ideal $\mathfrak{b}$ in the *inverse* class $C^{-1}$, and let $\alpha \in \mathfrak{b}$ be the element just produced. Then $(\alpha) \subseteq \mathfrak{b}$, so $(\alpha) = \mathfrak{b}\,\mathfrak{a}$ for an integral ideal $\mathfrak{a}$ whose class is $[(\alpha)]\cdot$class$(\mathfrak{b})^{-1} = 1\cdot(C^{-1})^{-1} = C$ (since $(\alpha)$ is principal and $\mathfrak{b}\in C^{-1}$), and multiplicativity of the norm gives $N(\mathfrak{a}) = |N_{K/\mathbb{Q}}(\alpha)|/N(\mathfrak{b}) \le (4/\pi)^{r_2}(n!/n^n)\sqrt{|d_K|} = M_K$. Thus $C$ contains an integral ideal of norm $\le M_K$. $\square$`,
  },
  {
    id: 'class-number-finiteness',
    label: 'Finiteness of the Class Number',
    title: 'Finiteness of the Class Number',
    kind: 'theorem',
    tags: ['Algebraic Number Theory'],
    dependencies: ['ideal-class-group', 'minkowski-bound', 'ideal-norm'],
    description: String.raw`The class group, a priori only an abstract quotient of an infinitely generated group, is in fact finite for every number field. The proof is a two-step squeeze: Minkowski's bound puts an explicit ceiling on the norm of an ideal one may choose in each class, and only finitely many ideals lie below any given norm. So the classes are represented by a finite list of ideals, and the class number is finite. This is a cornerstone of the theory: it makes the class number a genuine arithmetic invariant, computable in principle by checking the finitely many primes below the Minkowski bound.`,
    statement: String.raw`For every number field $K$, the ideal class group $\mathrm{Cl}(K)$ is **finite**; equivalently, the class number $h_K = |\mathrm{Cl}(K)|$ is a finite positive integer.`,
    proof: String.raw`By the **minkowski-bound**, every ideal class of $\mathrm{Cl}(K)$ contains an integral ideal $\mathfrak{a}$ with $N(\mathfrak{a}) \le M_K$, where $M_K = (4/\pi)^{r_2}(n!/n^n)\sqrt{|d_K|}$ is a fixed real number depending only on $K$. So the finitely-many norm classes below $M_K$ already represent every element of $\mathrm{Cl}(K)$.

It remains to see there are only finitely many integral ideals of bounded norm. By the **ideal-norm**, any ideal $\mathfrak{a}$ with $N(\mathfrak{a}) = m$ contains the integer $m$ (since $|\mathcal{O}_K/\mathfrak{a}| = m$ kills the quotient), so $\mathfrak{a}$ corresponds to an ideal of the finite ring $\mathcal{O}_K/(m)$, of which there are finitely many; hence only finitely many ideals have norm $m$, and so only finitely many have norm $\le M_K$. Therefore the surjection from this finite set of ideals onto $\mathrm{Cl}(K)$ shows $\mathrm{Cl}(K)$ is finite. $\square$`,
  },
  {
    id: 'dirichlet-unit-theorem',
    label: "Dirichlet's Unit Theorem",
    title: "Dirichlet's Unit Theorem",
    kind: 'theorem',
    tags: ['Algebraic Number Theory'],
    dependencies: ['ring-of-integers', 'embeddings-number-field', 'field-norm-trace'],
    description: String.raw`The other fundamental finiteness/structure result describes the multiplicative units of $\mathcal{O}_K$ — the invertible algebraic integers. Unlike the additive structure (a free $\mathbb{Z}$-module of rank $n$), the unit group is a finitely generated abelian group whose free rank depends only on the signature: real embeddings and pairs of complex embeddings each contribute, with one relation from the product formula. The torsion part is just the roots of unity in $K$. For real quadratic fields this is the existence of a single fundamental unit, intimately tied to the solutions of Pell's equation $x^2 - d y^2 = \pm 1$.`,
    statement: String.raw`Let $K$ be a number field of signature $(r_1, r_2)$, so $[K:\mathbb{Q}] = r_1 + 2 r_2$. Then the unit group of $\mathcal{O}_K$ is
$$\mathcal{O}_K^\times \cong \mu_K \times \mathbb{Z}^{\,r_1 + r_2 - 1},$$
where $\mu_K$ is the (finite cyclic) group of roots of unity in $K$. In particular the free rank is $r := r_1 + r_2 - 1$.`,
    proof: String.raw`*Sketch via the logarithmic embedding, naming the deep inputs.* Order the **embeddings** (from **embeddings-number-field**) as $\sigma_1, \dots, \sigma_{r_1}$ (real) and $\sigma_{r_1+1}, \dots, \sigma_{r_1+r_2}$ (one per complex pair), and define the **logarithmic embedding** $L : \mathcal{O}_K^\times \to \mathbb{R}^{r_1+r_2}$ by $L(u) = (\log|\sigma_1(u)|, \dots, \log|\sigma_{r_1}(u)|, 2\log|\sigma_{r_1+1}(u)|, \dots, 2\log|\sigma_{r_1+r_2}(u)|)$.

*Image lies in a hyperplane.* For a unit $u$, the **field norm** $N_{K/\mathbb{Q}}(u) = \prod_i \sigma_i(u) = \pm 1$ (an integer dividing $1$), so $\sum_k L(u)_k = \log|N_{K/\mathbb{Q}}(u)| = 0$: the image of $L$ lies in the hyperplane $H = \{x : \sum_k x_k = 0\}$, of dimension $r_1 + r_2 - 1 = r$.

*Kernel is the roots of unity.* $L(u) = 0$ means $|\sigma_i(u)| = 1$ for all $i$, so $u$ maps into a bounded region of the Minkowski space and, being an algebraic integer, lies in a finite set closed under multiplication — hence $\ker L = \mu_K$ is finite, thus cyclic and equal to the roots of unity in $K$.

*Image is a full lattice in $H$.* This is the analytic heart, proved by the **geometry of numbers** (Minkowski's lattice-point theorem applied to the Minkowski embedding): $L(\mathcal{O}_K^\times)$ is a discrete subgroup of $H$ (units of bounded archimedean size are finite in number) that spans $H$ as a real vector space (one produces, for each coordinate direction, a unit whose logarithmic vector has a strictly dominant entry, via a pigeonhole/lattice-point argument on ideals of bounded norm). A discrete subgroup spanning $\mathbb{R}^r$ is a free $\mathbb{Z}$-module of rank $r$.

Therefore $\mathcal{O}_K^\times / \mu_K \cong L(\mathcal{O}_K^\times) \cong \mathbb{Z}^r$ with $r = r_1 + r_2 - 1$, and the extension splits because $\mathbb{Z}^r$ is free, giving $\mathcal{O}_K^\times \cong \mu_K \times \mathbb{Z}^{r_1+r_2-1}$. $\square$`,
  },

  // ── Galois-theoretic and local structure ───────────────────────────────────
  {
    id: 'frobenius-element',
    label: 'Frobenius Element',
    title: 'Frobenius Element',
    kind: 'definition',
    tags: ['Algebraic Number Theory'],
    dependencies: ['ramification', 'galois-theory'],
    description: String.raw`When $K/\mathbb{Q}$ is Galois, the Galois group acts on the primes above a fixed rational prime, and for the unramified ones this action pins down a distinguished element. Reduction modulo a prime $\mathfrak{p}$ turns the field automorphisms into automorphisms of the residue field $\mathbb{F}_{p^f}$, whose Galois group is cyclic generated by $x \mapsto x^p$; the automorphism of $K$ inducing this raising-to-the-$p$-th-power is the Frobenius. Up to conjugacy it depends only on $p$, and it encodes exactly how $p$ splits. Tracking Frobenius across all primes is the organizing idea of class field theory and the Langlands program, and in the quadratic case it is quadratic reciprocity.`,
    definition: String.raw`Let $K/\mathbb{Q}$ be a finite **Galois** extension with $G = \operatorname{Gal}(K/\mathbb{Q})$ (from **galois-theory**), and let $p$ be a prime **unramified** in $K$ (every $e_i = 1$, via **ramification**). Fix a prime $\mathfrak{p}$ of $\mathcal{O}_K$ above $p$; the decomposition group $D_\mathfrak{p} = \{\sigma \in G : \sigma\mathfrak{p} = \mathfrak{p}\}$ acts on the residue **finite field** $\kappa(\mathfrak{p}) = \mathcal{O}_K/\mathfrak{p} = \mathbb{F}_{p^f}$, and (since $p$ is unramified) the natural map $D_\mathfrak{p} \to \operatorname{Gal}(\mathbb{F}_{p^f}/\mathbb{F}_p)$ is an isomorphism onto a cyclic group generated by the $p$-power map. The **Frobenius element** $\operatorname{Frob}_\mathfrak{p} \in D_\mathfrak{p} \subseteq G$ is the unique automorphism with
$$\operatorname{Frob}_\mathfrak{p}(x) \equiv x^{p} \pmod{\mathfrak{p}} \quad\text{for all } x \in \mathcal{O}_K.$$
Varying $\mathfrak{p}$ over the primes above $p$ conjugates $\operatorname{Frob}_\mathfrak{p}$, so $p$ determines a well-defined **conjugacy class** $\operatorname{Frob}_p \subseteq G$ — a single element when $G$ is abelian. The cycle type of $\operatorname{Frob}_p$ records the splitting of $p$.`,
  },
  {
    id: 'p-adic-numbers',
    label: 'p-adic Numbers',
    title: 'p-adic Numbers',
    kind: 'definition',
    tags: ['Algebraic Number Theory'],
    dependencies: ['rationals', 'absolute-value', 'complete-metric-space', 'cauchy-sequence'],
    description: String.raw`Alongside the familiar completion of $\mathbb{Q}$ to $\mathbb{R}$, each prime $p$ supplies a different completion. The $p$-adic absolute value declares a rational *small* when it is divisible by a high power of $p$; completing $\mathbb{Q}$ in this metric yields the field $\mathbb{Q}_p$, where congruences modulo high powers of $p$ become genuine limits and infinite power series in $p$ converge. This gives number theory a local analysis at each prime. Ostrowski's theorem says these — together with the usual absolute value — are essentially all the absolute values on $\mathbb{Q}$, and the local–global philosophy studies Diophantine problems by assembling information from $\mathbb{R}$ and every $\mathbb{Q}_p$.`,
    definition: String.raw`Fix a prime $p$. For $0 \neq x \in \mathbb{Q}$ write $x = p^v\,\tfrac{a}{b}$ with $p \nmid ab$; the **$p$-adic valuation** is $v_p(x) = v$ and the **$p$-adic absolute value** is the **absolute value** $|x|_p = p^{-v_p(x)}$ (with $|0|_p = 0$). It satisfies the ultrametric inequality $|x+y|_p \le \max(|x|_p, |y|_p)$, so it defines a metric $d_p(x,y) = |x-y|_p$ on $\mathbb{Q}$. The field of **$p$-adic numbers** $\mathbb{Q}_p$ is the **completion** of $\mathbb{Q}$ for this metric: the **complete-metric-space** of equivalence classes of $p$-adic **Cauchy sequences**, with field operations extended by continuity. Its valuation ring $\mathbb{Z}_p = \{x : |x|_p \le 1\}$ — the **$p$-adic integers** — is the inverse limit $\varprojlim \mathbb{Z}/p^n\mathbb{Z}$.`,
  },
  {
    id: 'cyclotomic-field',
    label: 'Cyclotomic Field',
    title: 'Cyclotomic Field',
    kind: 'definition',
    tags: ['Algebraic Number Theory'],
    dependencies: ['number-field', 'galois-theory', 'ring-of-integers', 'frobenius-element', 'ramification'],
    description: String.raw`The most concrete and computable number fields are obtained by adjoining a root of unity to $\mathbb{Q}$. The resulting cyclotomic field $\mathbb{Q}(\zeta_n)$ has an exceptionally clean structure: its degree is $\varphi(n)$, its Galois group is the explicit abelian group $(\mathbb{Z}/n\mathbb{Z})^\times$, and its ring of integers is exactly $\mathbb{Z}[\zeta_n]$. Because they are abelian, cyclotomic fields are the testing ground for class field theory — and the Kronecker–Weber theorem reveals their universality: every abelian extension of $\mathbb{Q}$ is contained in one. They are also the natural home of Fermat's Last Theorem and the higher reciprocity laws.`,
    definition: String.raw`Let $\zeta_n = e^{2\pi i/n}$ be a primitive $n$-th root of unity. The **cyclotomic field** is the **number field** $\mathbb{Q}(\zeta_n) = \mathbb{Q}[x]/(\Phi_n(x))$, where $\Phi_n$ is the (irreducible, degree $\varphi(n)$) cyclotomic polynomial; thus $[\mathbb{Q}(\zeta_n):\mathbb{Q}] = \varphi(n)$. By **galois-theory** the extension is **Galois** with
$$\operatorname{Gal}(\mathbb{Q}(\zeta_n)/\mathbb{Q}) \cong (\mathbb{Z}/n\mathbb{Z})^\times, \qquad \sigma_a : \zeta_n \mapsto \zeta_n^a,$$
an **abelian** group; its **ring of integers** is $\mathcal{O}_{\mathbb{Q}(\zeta_n)} = \mathbb{Z}[\zeta_n]$. A prime $p \nmid n$ is unramified and its **Frobenius** is $\sigma_p$, so its splitting depends only on $p \bmod n$. The **Kronecker–Weber theorem** states conversely that every finite abelian extension of $\mathbb{Q}$ lies in some $\mathbb{Q}(\zeta_n)$.`,
  },
]
