import type { MathNode } from '../types'

export const STOCHASTIC_PROCESSES_NODES: MathNode[] = [
  // ── Processes & information ────────────────────────────────────────────────
  {
    id: 'stochastic-process',
    label: 'Stochastic Process',
    title: 'Stochastic Process',
    kind: 'definition',
    tags: ['Stochastic Processes'],
    dependencies: ['random-variable', 'probability-space'],
    description: String.raw`A single random variable captures one uncertain quantity; a stochastic process captures a whole system evolving by chance, by bundling together one random variable for each instant of time. Fixing the outcome $\omega$ and letting time run traces out a **path** — the trajectory one actually observes — while fixing the time and letting $\omega$ vary gives back an ordinary random variable. The law of the process is pinned down by its **finite-dimensional distributions**, the joint laws of finitely many of the $X_t$ at once; Kolmogorov's extension theorem says any consistent family of these arises from an actual process.`,
    definition: String.raw`Fix a **probability space** $(\Omega, \mathcal{F}, P)$ and an index set $T$ (typically $\mathbb{N}$, $\mathbb{Z}_{\ge 0}$, or $[0, \infty)$, read as time). A **stochastic process** is a family $(X_t)_{t \in T}$ of **random variables** $X_t : \Omega \to \mathbb{R}^d$ on the common space. For fixed $\omega \in \Omega$ the map $t \mapsto X_t(\omega)$ is a **sample path**. The **finite-dimensional distributions** are the laws of the vectors $(X_{t_1}, \dots, X_{t_n})$ for finite $\{t_1, \dots, t_n\} \subseteq T$; by Kolmogorov's extension theorem a consistent family of such distributions determines a process. A process can equivalently be viewed as a single random variable $\omega \mapsto (X_t(\omega))_{t \in T}$ valued in a path space.`,
  },
  {
    id: 'filtration',
    label: 'Filtration',
    title: 'Filtration & Adapted Process',
    kind: 'definition',
    tags: ['Stochastic Processes'],
    dependencies: ['stochastic-process', 'sigma-algebra'],
    description: String.raw`To reason about decisions made "as time unfolds," one needs a precise notion of the information available at each instant. A filtration records this: an increasing family of $\sigma$-algebras, $\mathcal{F}_t$ being everything observable by time $t$. The family only grows, since information is never lost. A process is **adapted** when its value at time $t$ is already known once the present has arrived — measurable with respect to $\mathcal{F}_t$. This bookkeeping of accumulating information is the stage on which martingales and stopping times are defined.`,
    definition: String.raw`A **filtration** on $(\Omega, \mathcal{F}, P)$ is a family $(\mathcal{F}_t)_{t \in T}$ of sub-$\sigma$-algebras of $\mathcal{F}$ that is increasing: $\mathcal{F}_s \subseteq \mathcal{F}_t$ whenever $s \le t$. A **stochastic process** $(X_t)$ is **adapted** to $(\mathcal{F}_t)$ if each $X_t$ is $\mathcal{F}_t$-measurable. The smallest filtration to which $(X_t)$ is adapted is its **natural filtration** $\mathcal{F}_t^X = \sigma(X_s : s \le t)$, the $\sigma$-algebra generated by the process up to time $t$. A quadruple $(\Omega, \mathcal{F}, (\mathcal{F}_t), P)$ is a **filtered probability space**.`,
  },

  // ── Markov chains ──────────────────────────────────────────────────────────
  {
    id: 'markov-chain',
    label: 'Markov Chain',
    title: 'Markov Chain',
    kind: 'definition',
    tags: ['Stochastic Processes'],
    dependencies: ['stochastic-process', 'conditional-probability'],
    description: String.raw`Many random dynamics are *memoryless*: to predict tomorrow you need only today's state, not the entire history of how you got there. A Markov chain formalizes this. Given the present, the future is conditionally independent of the past — the **Markov property**. For a chain on a finite or countable state space the dynamics reduce to a single table of one-step probabilities, and multi-step behavior is read off from its matrix powers. This is the basic model of random walks, queueing, population genetics, and the sampling engine behind Markov chain Monte Carlo.`,
    definition: String.raw`Let $S$ be a countable **state space**. A discrete-time process $(X_n)_{n \ge 0}$ with values in $S$ is a (time-homogeneous) **Markov chain** if for all $n$ and all states with $P(X_n = i, \dots, X_0 = i_0) > 0$ it has the **Markov property**
$$P(X_{n+1} = j \mid X_n = i, X_{n-1} = i_{n-1}, \dots, X_0 = i_0) = P(X_{n+1} = j \mid X_n = i) =: p_{ij},$$
the right side independent of $n$. The numbers $p_{ij} \ge 0$ with $\sum_{j} p_{ij} = 1$ form the **transition matrix**, and the chain is determined by an initial law on $S$ together with these one-step probabilities.`,
  },
  {
    id: 'transition-matrix',
    label: 'Transition Matrix',
    title: 'Transition Matrix & Chapman–Kolmogorov',
    kind: 'proposition',
    tags: ['Stochastic Processes'],
    dependencies: ['markov-chain', 'matrix', 'conditional-probability', 'law-of-total-probability'],
    description: String.raw`The one-step probabilities of a Markov chain assemble into a stochastic matrix, and the central computational fact is that probabilities of moving across several steps are obtained simply by matrix multiplication: the $n$-step transition probabilities are the entries of the $n$-th power of the one-step matrix. The underlying identity — that to go from $i$ to $j$ in $m+n$ steps one passes through some intermediate state after $m$ steps — is the Chapman–Kolmogorov equation, the discrete analogue of the semigroup property of a flow.`,
    statement: String.raw`Let $P = (p_{ij})_{i,j \in S}$ be the **transition matrix** of a **Markov chain**, so $p_{ij} \ge 0$ and each row sums to $1$ (a **stochastic matrix**). Writing $p_{ij}^{(n)} = P(X_{m+n} = j \mid X_m = i)$ for the $n$-step probabilities, one has $p_{ij}^{(n)} = (P^n)_{ij}$, and the **Chapman–Kolmogorov equation** holds:
$$p_{ij}^{(m+n)} = \sum_{k \in S} p_{ik}^{(m)}\, p_{kj}^{(n)}, \qquad \text{i.e. } P^{m+n} = P^m P^n.$$`,
    proof: String.raw`That each row sums to $1$ is the requirement $\sum_j p_{ij} = \sum_j P(X_{1} = j \mid X_0 = i) = 1$, since $\{X_1 = j\}_{j \in S}$ partitions the event $\{X_0 = i\}$ (assuming $P(X_0 = i) > 0$, so the conditional probabilities are defined).

*Step 1: $p_{ij}^{(n)} = (P^n)_{ij}$ for all $n \ge 1$, by induction on $n$.* We must first see that $p_{ij}^{(n)} := P(X_{m+n} = j \mid X_m = i)$ is well-defined and independent of the base time $m$; this is established alongside the formula. The base case $n = 1$ is time-homogeneity, $P(X_{m+1} = j \mid X_m = i) = p_{ij} = (P^1)_{ij}$, which is part of the definition of a **Markov chain**. For the inductive step, suppose the claim holds for $n$. Fix $m$ with $P(X_m = i) > 0$ and condition on the state one step before the end, at time $m + n$, using the law of total probability over the partition $\{X_{m+n} = k\}_{k \in S}$ and the definition of **conditional probability**:
$$P(X_{m+n+1} = j \mid X_m = i) = \sum_{k \in S} P(X_{m+n+1} = j \mid X_{m+n} = k,\, X_m = i)\, P(X_{m+n} = k \mid X_m = i),$$
where the sum runs over states $k$ with $P(X_{m+n} = k,\, X_m = i) > 0$. Each such term has $P(X_{m+n+1} = j \mid X_{m+n} = k,\, X_m = i) = p_{kj}$: indeed, expanding $P(X_{m+n} = k, X_m = i)$ as a sum over full intermediate histories $(X_{m+1}, \dots, X_{m+n-1})$ and applying the one-step full-history **Markov property** $P(X_{m+n+1} = j \mid X_{m+n} = k, \dots, X_m = i, \dots) = p_{kj}$ to every history ending in $X_{m+n} = k$, the common factor $p_{kj}$ pulls out of the history-sum and cancels against $P(X_{m+n} = k, X_m = i)$. By the inductive hypothesis the second factor is $P(X_{m+n} = k \mid X_m = i) = p_{ik}^{(n)} = (P^n)_{ik}$, well-defined and $m$-independent. Hence $P(X_{m+n+1} = j \mid X_m = i) = \sum_k (P^n)_{ik}\, p_{kj} = (P^{n+1})_{ij}$, which is $m$-independent, completing the induction.

*Step 2: Chapman–Kolmogorov.* From Step 1 the $n$-step probabilities are the matrix powers, so the semigroup identity $P^{m+n} = P^m P^n$ for matrix multiplication reads entrywise as
$$p_{ij}^{(m+n)} = (P^{m+n})_{ij} = (P^m P^n)_{ij} = \sum_{k \in S} (P^m)_{ik}\,(P^n)_{kj} = \sum_{k \in S} p_{ik}^{(m)}\, p_{kj}^{(n)}. \qquad \square$$`
  },
  {
    id: 'stationary-distribution',
    label: 'Stationary Distribution',
    title: 'Stationary Distribution',
    kind: 'definition',
    tags: ['Stochastic Processes'],
    dependencies: ['markov-chain', 'transition-matrix', 'eigenvalue-eigenvector'],
    description: String.raw`A stationary distribution is an equilibrium for a Markov chain: a probability vector over the states that the dynamics leave unchanged. Start the chain in it and the distribution stays put forever. For a well-connected chain it is unique, the chain converges to it from any start, and the stationary weight of a state equals the long-run fraction of time the chain spends there. This convergence to equilibrium is the principle behind PageRank (the stationary distribution of a random surfer) and Markov chain Monte Carlo (designing a chain whose equilibrium is a target distribution).`,
    definition: String.raw`A **stationary distribution** of a **Markov chain** with **transition matrix** $P$ is a probability vector $\pi = (\pi_i)_{i \in S}$ — $\pi_i \ge 0$, $\sum_i \pi_i = 1$ — left fixed by $P$:
$$\pi_j = \sum_{i \in S} \pi_i\, p_{ij} \quad \text{for all } j, \qquad \text{i.e.} \qquad \pi P = \pi.$$
Thus $\pi$ is a left **eigenvector** of $P$ with eigenvalue $1$, normalized to a probability vector. If the chain is irreducible and positive recurrent (in particular, any irreducible finite chain), $\pi$ exists and is unique with $\pi_i = 1/\mathbb{E}_i[\tau_i]$ (the reciprocal mean return time); if moreover the chain is aperiodic, $p_{ij}^{(n)} \to \pi_j$ for all $i, j$ as $n \to \infty$.`,
  },
  {
    id: 'random-walk',
    label: 'Random Walk',
    title: 'Random Walk',
    kind: 'definition',
    tags: ['Stochastic Processes'],
    dependencies: ['stochastic-process', 'independence', 'expectation', 'markov-chain', 'martingale'],
    description: String.raw`The simplest interesting process is a running total of independent random steps: take a step, take another step drawn from the same law independently of the first, and keep adding. This single construction is at once a Markov chain (the next position depends only on the current one) and, when the steps are centered, a martingale (the position is on average where it is now). On the integer lattice the symmetric nearest-neighbor walk returns to its start infinitely often in dimensions one and two but escapes to infinity in dimension three and higher — Pólya's recurrence theorem — and zoomed out, the walk converges to Brownian motion.`,
    definition: String.raw`Let $\xi_1, \xi_2, \dots$ be **independent**, identically distributed $\mathbb{R}^d$-valued steps. The **random walk** with these steps is the process of partial sums
$$S_0 = 0, \qquad S_n = \xi_1 + \xi_2 + \cdots + \xi_n \quad (n \ge 1).$$
It is a time-homogeneous **Markov chain**, since $S_{n+1} = S_n + \xi_{n+1}$ with $\xi_{n+1}$ independent of $S_0, \dots, S_n$. The **simple symmetric random walk** on $\mathbb{Z}^d$ takes $\xi$ uniform over the $2d$ unit lattice vectors. When $\mathbb{E}[\xi_1] = 0$ (and $\mathbb{E}|\xi_1| < \infty$), $(S_n)$ is a **martingale** for its natural filtration; if instead $\mathbb{E}[\xi_1] = \mu$, then $S_n - n\mu$ is a martingale.`,
  },

  // ── Martingales & stopping ─────────────────────────────────────────────────
  {
    id: 'martingale',
    label: 'Martingale',
    title: 'Martingale',
    kind: 'definition',
    tags: ['Stochastic Processes'],
    dependencies: ['filtration', 'conditional-expectation'],
    description: String.raw`A martingale models a fair game: knowing the entire past, your best forecast of the next value is exactly the current value — no systematic gain or loss is expected. The definition replaces the single conditioning event of elementary probability by conditioning on the whole information $\sigma$-algebra $\mathcal{F}_n$, using conditional expectation. Tilting the balance gives the two one-sided cousins: a submartingale is a favorable game (drifts up on average) and a supermartingale an unfavorable one (drifts down). Martingales obey strong convergence theorems and maximal inequalities and are the structural backbone of modern probability and of arbitrage-free pricing in finance.`,
    definition: String.raw`Let $(\mathcal{F}_n)$ be a **filtration**. An adapted, integrable process $(X_n)$ — each $X_n$ is $\mathcal{F}_n$-measurable with $\mathbb{E}[|X_n|] < \infty$ — is a **martingale** if
$$\mathbb{E}[X_{n+1} \mid \mathcal{F}_n] = X_n \quad \text{for all } n,$$
the **conditional expectation** of the next value given the past being the present value. It is a **submartingale** if $\mathbb{E}[X_{n+1} \mid \mathcal{F}_n] \ge X_n$ and a **supermartingale** if $\mathbb{E}[X_{n+1} \mid \mathcal{F}_n] \le X_n$. By the tower property, $\mathbb{E}[X_{n+k} \mid \mathcal{F}_n] = X_n$ for all $k \ge 0$ in the martingale case, and in particular $\mathbb{E}[X_n] = \mathbb{E}[X_0]$ is constant.`,
  },
  {
    id: 'stopping-time',
    label: 'Stopping Time',
    title: 'Stopping Time',
    kind: 'definition',
    tags: ['Stochastic Processes'],
    dependencies: ['filtration'],
    description: String.raw`A stopping time is a random time chosen by a rule that cannot peek into the future: whether to stop by time $t$ must be decidable from the information available by time $t$ alone. Hitting times — "the first moment the process reaches a given level" — are the prototype, since reaching the level is detected as it happens. By contrast "the last visit to a state" is not a stopping time, as recognizing a visit as the last one requires seeing the whole future. Stopping times formalize admissible strategies, and they are exactly what makes the optional stopping theorem and the strong Markov property work.`,
    definition: String.raw`Given a **filtration** $(\mathcal{F}_t)_{t \in T}$, a random variable $\tau : \Omega \to T \cup \{\infty\}$ is a **stopping time** if
$$\{\tau \le t\} \in \mathcal{F}_t \quad \text{for every } t \in T$$
(equivalently, in discrete time, $\{\tau = n\} \in \mathcal{F}_n$ for every $n$). Its **stopped $\sigma$-algebra** is $\mathcal{F}_\tau = \{\, A \in \mathcal{F} : A \cap \{\tau \le t\} \in \mathcal{F}_t \text{ for all } t \,\}$, the information known up to the random time $\tau$. For an adapted process $(X_n)$ and $B$ a measurable set of states, the **hitting time** $\tau_B = \inf\{ n \ge 0 : X_n \in B\}$ is a stopping time, since $\{\tau_B \le n\} = \bigcup_{k \le n}\{X_k \in B\} \in \mathcal{F}_n$.`,
  },
  {
    id: 'optional-stopping-theorem',
    label: 'Optional Stopping',
    title: 'Optional Stopping Theorem',
    kind: 'theorem',
    tags: ['Stochastic Processes'],
    dependencies: ['martingale', 'stopping-time', 'dominated-convergence-theorem'],
    description: String.raw`A fair game stays fair even if you are allowed to quit at a cleverly chosen moment, so long as the rule for quitting cannot see the future: the expected value at the stopping time equals the starting value. This is false without a side condition — a gambler who plays until ahead can have positive expected winnings only because that strategy risks unbounded losses or unbounded time — and the theorem isolates exactly the hypotheses (a bounded stopping time, or suitable integrability) that rule such schemes out. It is the master computational tool for hitting probabilities and expected hitting times, including the classical gambler's ruin, and it underlies the no-arbitrage principle in pricing.`,
    statement: String.raw`Let $(X_n)_{n \ge 0}$ be a **martingale** for $(\mathcal{F}_n)$ and $\tau$ a **stopping time**. Then $\mathbb{E}[X_\tau] = \mathbb{E}[X_0]$ provided any one of the following holds: (a) $\tau$ is bounded, $\tau \le N$ a.s.; (b) $\tau < \infty$ a.s. and $(X_{n \wedge \tau})_n$ is uniformly bounded, $|X_{n \wedge \tau}| \le C$; or (c) $\mathbb{E}[\tau] < \infty$ and the increments are bounded, $|X_{n+1} - X_n| \le C$ on $\{\tau > n\}$. (For a submartingale, $=$ becomes $\ge$ in (a); for a supermartingale, $\le$.)`,
    proof: String.raw`*The stopped process is a martingale.* Write $X_n^\tau := X_{n \wedge \tau}$. Then $X_{n+1}^\tau - X_n^\tau = \mathbf{1}_{\{\tau > n\}}(X_{n+1} - X_n)$, and the indicator $\mathbf{1}_{\{\tau > n\}} = 1 - \mathbf{1}_{\{\tau \le n\}}$ is $\mathcal{F}_n$-measurable because $\tau$ is a **stopping time**. Hence, pulling the $\mathcal{F}_n$-measurable factor out of the **conditional expectation** and using the **martingale** property $\mathbb{E}[X_{n+1} - X_n \mid \mathcal{F}_n] = 0$,
$$\mathbb{E}[X_{n+1}^\tau - X_n^\tau \mid \mathcal{F}_n] = \mathbf{1}_{\{\tau > n\}}\,\mathbb{E}[X_{n+1} - X_n \mid \mathcal{F}_n] = 0.$$
So $(X_n^\tau)$ is itself a martingale, whence $\mathbb{E}[X_{n \wedge \tau}] = \mathbb{E}[X_0^\tau] = \mathbb{E}[X_0]$ for every $n$.

*Passing to the limit.* In case (a) take $n = N \ge \tau$: then $X_{N \wedge \tau} = X_\tau$ and the claim is immediate. In cases (b) and (c), $\tau < \infty$ a.s. gives $X_{n \wedge \tau} \to X_\tau$ pointwise a.s. as $n \to \infty$. Under (b) the variables $X_{n \wedge \tau}$ are dominated by the constant $C$, so the **dominated convergence theorem** gives $\mathbb{E}[X_{n \wedge \tau}] \to \mathbb{E}[X_\tau]$, and the left side is constantly $\mathbb{E}[X_0]$. Under (c) write $X_{n \wedge \tau} = X_0 + \sum_{k=0}^{n-1}\mathbf{1}_{\{\tau > k\}}(X_{k+1} - X_k)$; the summands are bounded by $C\,\mathbf{1}_{\{\tau > k\}}$, so $|X_{n \wedge \tau}| \le |X_0| + C\sum_{k \ge 0}\mathbf{1}_{\{\tau > k\}} = |X_0| + C\tau$, an integrable dominating function since $\mathbb{E}[\tau] < \infty$; again **dominated convergence** yields $\mathbb{E}[X_\tau] = \lim_n \mathbb{E}[X_{n \wedge \tau}] = \mathbb{E}[X_0]$. The sub/supermartingale variants replace the equality $\mathbb{E}[X_{n+1} - X_n \mid \mathcal{F}_n] = 0$ by the corresponding inequality, preserving the direction throughout. $\square$`,
  },

  // ── Continuous-time processes ──────────────────────────────────────────────
  {
    id: 'poisson-process',
    label: 'Poisson Process',
    title: 'Poisson Process',
    kind: 'definition',
    tags: ['Stochastic Processes'],
    dependencies: ['stochastic-process', 'independence'],
    description: String.raw`The Poisson process is the canonical model of events arriving completely at random in continuous time: radioactive decays, phone calls into a switchboard, customers joining a queue. Three equivalent descriptions converge on the same object — increments over disjoint intervals are independent and the count in an interval is Poisson with mean proportional to its length; the waiting times between successive arrivals are independent exponentials; or arrivals occur at a constant rate with no two coinciding. The exponential gaps encode memorylessness — having waited a while for the next event tells you nothing about how much longer you will wait — which makes it the simplest continuous-time Markov jump process.`,
    definition: String.raw`A **Poisson process** of rate $\lambda > 0$ is a process $(N_t)_{t \ge 0}$ counting events, with $N_0 = 0$ and right-continuous nondecreasing integer-valued paths, characterized by either of these equivalent conditions:
$$\text{(i) independent increments, and } N_t - N_s \sim \mathrm{Poisson}(\lambda(t - s)) \text{ for } s < t;$$
$$\text{(ii) the inter-arrival times } T_1, T_2 - T_1, T_3 - T_2, \dots \text{ are i.i.d. } \mathrm{Exponential}(\lambda).$$
Here "**independent increments**" means that for $t_0 < t_1 < \cdots < t_n$ the increments $N_{t_1} - N_{t_0}, \dots, N_{t_n} - N_{t_{n-1}}$ are **independent**. It is the prototypical continuous-time Markov jump process, and $N_t - \lambda t$ is a martingale.`,
  },
  {
    id: 'brownian-motion',
    label: 'Brownian Motion',
    title: 'Brownian Motion (Wiener Process)',
    kind: 'definition',
    tags: ['Stochastic Processes'],
    dependencies: ['stochastic-process', 'normal-distribution', 'independence', 'martingale'],
    description: String.raw`Brownian motion is the continuous-time, continuous-path analogue of the random walk, named for the erratic jiggling of pollen grains in water. It starts at the origin, moves by increments that are independent over disjoint time intervals, stationary (their law depends only on the elapsed time), and Gaussian with variance equal to the elapsed time; its paths are continuous yet so rough as to be nowhere differentiable. It is the universal scaling limit of random walks (Donsker's theorem), simultaneously a martingale and a Markov process, the integrator of stochastic calculus, and the bridge to analysis: its transition density is the Gaussian heat kernel, so it solves the heat equation. Its existence is a theorem (Wiener), not part of the definition.`,
    definition: String.raw`A standard (one-dimensional) **Brownian motion**, or **Wiener process**, is a process $(W_t)_{t \ge 0}$ with: (i) $W_0 = 0$ a.s.; (ii) **independent increments** — for $0 \le t_0 < \cdots < t_n$ the increments $W_{t_1} - W_{t_0}, \dots, W_{t_n} - W_{t_{n-1}}$ are **independent**; (iii) **stationary Gaussian increments** — $W_t - W_s \sim \mathcal{N}(0, t - s)$ for $0 \le s < t$, a **normal distribution** with mean $0$ and variance $t - s$; (iv) continuous sample paths $t \mapsto W_t$, almost surely. Such a process exists (Wiener's theorem); its paths are almost surely nowhere differentiable. A $d$-dimensional Brownian motion has independent standard one-dimensional coordinates. $(W_t)$ is a martingale, and so is $W_t^2 - t$.`,
  },
  {
    id: 'quadratic-variation',
    label: 'Quadratic Variation',
    title: 'Quadratic Variation of Brownian Motion',
    kind: 'proposition',
    tags: ['Stochastic Processes'],
    dependencies: ['brownian-motion', 'variance', 'borel-cantelli-lemma', 'markov-inequality'],
    description: String.raw`Ordinary smooth functions have zero quadratic variation: the sum of squared increments over a partition vanishes as the mesh shrinks. Brownian motion is different. Because each increment over a tiny interval of length $\Delta t$ has standard deviation of order $\sqrt{\Delta t}$, its square has expectation $\Delta t$, and summing across a partition of $[0,t]$ gives total expectation $t$ that does *not* die out. The squared fluctuations conspire to add up to exactly $t$. This single fact — written $(dW)^2 = dt$ — is precisely what forces the correction term in Itô's formula and is the reason Brownian paths, having infinite ordinary variation, still admit a calculus.`,
    statement: String.raw`Let $(W_t)$ be a standard **Brownian motion** and, for a partition $\Pi = \{0 = t_0 < t_1 < \cdots < t_n = t\}$ of $[0, t]$ with mesh $\|\Pi\| = \max_k (t_k - t_{k-1})$, set $Q_\Pi = \sum_{k=1}^n (W_{t_k} - W_{t_{k-1}})^2$. Then $Q_\Pi \to t$ in $L^2$ as $\|\Pi\| \to 0$; along any sequence of refining partitions with $\sum_m \|\Pi_m\| < \infty$ the convergence is almost sure. Symbolically the **quadratic variation** of $W$ on $[0,t]$ is $\langle W\rangle_t = t$.`,
    proof: String.raw`Write $\Delta_k = W_{t_k} - W_{t_{k-1}}$ and $\delta_k = t_k - t_{k-1}$. By the increment law of **Brownian motion**, $\Delta_k \sim \mathcal{N}(0, \delta_k)$, so $\mathbb{E}[\Delta_k^2] = \delta_k$ and the increments over disjoint intervals are independent. Hence $\mathbb{E}[Q_\Pi] = \sum_k \delta_k = t$. For the $L^2$ statement, by independence the terms $\Delta_k^2 - \delta_k$ are uncorrelated, so the **variance** of $Q_\Pi$ is additive:
$$\mathbb{E}\bigl[(Q_\Pi - t)^2\bigr] = \sum_{k=1}^n \operatorname{Var}(\Delta_k^2) = \sum_{k=1}^n 2\delta_k^2 \le 2\|\Pi\| \sum_{k=1}^n \delta_k = 2\|\Pi\|\, t,$$
using $\operatorname{Var}(\Delta_k^2) = \mathbb{E}[\Delta_k^4] - \delta_k^2 = 3\delta_k^2 - \delta_k^2 = 2\delta_k^2$ for the centered normal $\Delta_k$ (its fourth moment is $3\delta_k^2$). As $\|\Pi\| \to 0$ this bound $\to 0$, giving $Q_\Pi \to t$ in $L^2$. For a.s. convergence along partitions $\Pi_m$ with $\sum_m \|\Pi_m\| < \infty$, the same bound gives $\sum_m \mathbb{E}[(Q_{\Pi_m} - t)^2] \le 2t\sum_m \|\Pi_m\| < \infty$, so by **Markov's inequality** $\sum_m P(|Q_{\Pi_m} - t| > \varepsilon) < \infty$ for each $\varepsilon > 0$; the **Borel–Cantelli lemma** then forces $|Q_{\Pi_m} - t| > \varepsilon$ only finitely often a.s., i.e. $Q_{\Pi_m} \to t$ almost surely. $\square$`,
  },

  // ── Stochastic calculus ────────────────────────────────────────────────────
  {
    id: 'ito-calculus',
    label: 'Itô Calculus',
    title: 'Itô Integral & Itô’s Formula',
    kind: 'definition',
    tags: ['Stochastic Processes'],
    dependencies: ['brownian-motion', 'martingale', 'quadratic-variation'],
    description: String.raw`Brownian paths have infinite ordinary variation, so $\int H\,dW$ cannot be defined path-by-path as a Riemann–Stieltjes integral. Itô's resolution is to build the integral in the mean-square sense and — crucially — to evaluate the integrand at the *left* endpoint of each subinterval, so that it cannot anticipate the increment it multiplies. This non-anticipating choice makes the resulting integral a martingale, the defining feature of the theory. The price is that the ordinary chain rule fails: because the quadratic variation of $W$ is nonzero ($(dW)^2 = dt$), differentiating a function of $W$ acquires a second-order correction. That correction term, Itô's formula, is the heart of stochastic calculus.`,
    definition: String.raw`For an adapted process $H$ with $\mathbb{E}\int_0^T H_s^2\,ds < \infty$, the **Itô integral** $\int_0^t H_s\,dW_s$ is defined as the $L^2$-limit of the left-endpoint Riemann sums $\sum_k H_{t_{k-1}}(W_{t_k} - W_{t_{k-1}})$ as the partition mesh $\to 0$. It satisfies the **Itô isometry** $\mathbb{E}\bigl[\bigl(\int_0^t H\,dW\bigr)^2\bigr] = \mathbb{E}\int_0^t H_s^2\,ds$, and the process $t \mapsto \int_0^t H_s\,dW_s$ is a **martingale** with $\mathbb{E}\int_0^t H\,dW = 0$. For $f \in C^2$, **Itô's formula** is the stochastic chain rule
$$df(W_t) = f'(W_t)\,dW_t + \tfrac{1}{2}f''(W_t)\,dt,$$
the extra term $\tfrac12 f''\,dt$ arising from the **quadratic variation** $(dW)^2 = dt$. More generally, for $f(t, x) \in C^{1,2}$, $df(t, W_t) = \bigl(f_t + \tfrac12 f_{xx}\bigr)(t, W_t)\,dt + f_x(t, W_t)\,dW_t$.`,
  },
  {
    id: 'stochastic-differential-equation',
    label: 'Stochastic Differential Equation',
    title: 'Stochastic Differential Equation',
    kind: 'definition',
    tags: ['Stochastic Processes'],
    dependencies: ['ito-calculus', 'lipschitz-condition', 'heat-equation'],
    description: String.raw`A stochastic differential equation describes dynamics that are part deterministic, part random: an ordinary differential equation with a Brownian "noise" term added. The drift coefficient sets the average tendency of motion and the diffusion coefficient sets the strength of the noise; a solution is a process — a diffusion — interpreted through Itô calculus, since the noise term is an Itô integral. Under a Lipschitz condition on the coefficients there is a unique solution, by a stochastic version of the Picard iteration. SDEs model noisy systems from molecular motion to asset prices (the Black–Scholes model), and their transition densities solve partial differential equations — the Fokker–Planck and Kolmogorov equations — tying probability back to analysis.`,
    definition: String.raw`A **stochastic differential equation** driven by **Brownian motion** $W$ is
$$dX_t = b(t, X_t)\,dt + \sigma(t, X_t)\,dW_t, \qquad X_0 = x_0,$$
read as the Itô integral equation $X_t = x_0 + \int_0^t b(s, X_s)\,ds + \int_0^t \sigma(s, X_s)\,dW_s$ via **Itô calculus**, with **drift** $b$ and **diffusion coefficient** $\sigma$. If $b, \sigma$ satisfy a global **Lipschitz condition** and linear growth in $x$, there exists a unique (strong) solution (Itô's existence–uniqueness theorem, proved by Picard iteration with the Itô isometry in place of the deterministic estimate). The transition density $p(t, x)$ solves the **Fokker–Planck (forward Kolmogorov) equation** $\partial_t p = -\partial_x(b p) + \tfrac12\partial_x^2(\sigma^2 p)$; for $b = 0$, $\sigma = 1$ this is the **heat equation**, recovering Brownian motion.`,
  },
]
