import type { MathNode } from '../types'

export const TYPE_THEORY_NODES: MathNode[] = [
  // ── Untyped and simply typed calculi ────────────────────────────────────────
  {
    id: 'lambda-calculus',
    label: 'Lambda Calculus',
    title: 'Lambda Calculus',
    kind: 'definition',
    tags: ['Type Theory'],
    dependencies: ['function'],
    description: String.raw`Born from Church's analysis of computable functions, the **lambda calculus** is a minimal model of computation in which everything is a function. Three constructs suffice: variables, **abstraction** $\lambda x.\,M$ (forming the function $x \mapsto M$), and **application** $M\,N$ (feeding $N$ to $M$). Computation is **beta-reduction**, $(\lambda x.\,M)\,N \to M[x := N]$: copy the body, replacing the bound variable by the argument. Despite this austerity it is Turing-complete — every computable function is definable — and it is the substrate on which type theories are built.`,
    definition: String.raw`Fix a countable set of **variables**. The **terms** of the (untyped) lambda calculus are generated inductively:
$$M, N ::= x \;\mid\; \lambda x.\,M \;\mid\; M\,N,$$
i.e. every variable is a term, and if $M, N$ are terms and $x$ a variable then $\lambda x.\,M$ (abstraction) and $M\,N$ (application) are terms. In $\lambda x.\,M$ the abstraction **binds** every free occurrence of $x$ in $M$; terms are identified up to renaming of bound variables ($\alpha$-equivalence). **Capture-avoiding substitution** $M[x := N]$ replaces each free occurrence of $x$ in $M$ by $N$, first renaming bound variables of $M$ so that no free variable of $N$ is captured. The one computation rule is **$\beta$-reduction**,
$$(\lambda x.\,M)\,N \;\to_\beta\; M[x := N],$$
applied in any subterm; $\twoheadrightarrow_\beta$ denotes its reflexive–transitive closure and $=_\beta$ the generated equivalence.`,
  },
  {
    id: 'simply-typed-lambda-calculus',
    label: 'Simply Typed λ-Calculus',
    title: 'Simply Typed Lambda Calculus',
    kind: 'definition',
    tags: ['Type Theory'],
    dependencies: ['lambda-calculus'],
    description: String.raw`The untyped calculus admits nonsensical terms such as the self-application $\lambda x.\,x\,x$ and non-terminating loops. The **simply typed lambda calculus** (STLC) tames it by assigning **types** to terms: starting from base types and closing under the function-type former $A \to B$, it admits only **well-typed** terms. Typing is checked relative to a **context** of assumptions about free variables, via inference rules whose conclusions are **judgments** $\Gamma \vdash M : A$ ("in context $\Gamma$, term $M$ has type $A$"). Well-typed terms are exactly the meaningful programs, and — a theorem, not a definition — every one of them halts.`,
    definition: String.raw`Fix a set of **base types**. The **simple types** are generated by
$$A, B ::= \iota \;\mid\; A \to B \qquad (\iota \text{ a base type}),$$
with $\to$ associating to the right. A **context** $\Gamma = x_1 : A_1, \dots, x_n : A_n$ is a finite list of distinct variables tagged with types. The **typing judgment** $\Gamma \vdash M : A$ is generated by three rules:
$$\frac{(x : A) \in \Gamma}{\Gamma \vdash x : A}\,(\mathrm{var}) \qquad \frac{\Gamma,\, x : A \vdash M : B}{\Gamma \vdash \lambda x.\,M : A \to B}\,(\mathrm{abs}) \qquad \frac{\Gamma \vdash M : A \to B \quad \Gamma \vdash N : A}{\Gamma \vdash M\,N : B}\,(\mathrm{app}).$$
A term $M$ is **typable** if $\Gamma \vdash M : A$ holds for some $\Gamma, A$. Reduction is $\beta$-reduction inherited from the lambda calculus; this typed calculus is the term language whose typings are, under Curry–Howard, the proofs of implicational intuitionistic logic.`,
  },
  {
    id: 'type-preservation',
    label: 'Type Preservation',
    title: 'Type Preservation (Subject Reduction)',
    kind: 'lemma',
    tags: ['Type Theory'],
    dependencies: ['simply-typed-lambda-calculus'],
    description: String.raw`A typing should not be destroyed by running the program. **Subject reduction** is exactly this guarantee: if a well-typed term takes a $\beta$-step, the result is well-typed at the *same* type. It is the basic sanity property linking typing to computation, and it is the workhorse behind both strong normalization and the soundness of the Curry–Howard reading (where it says proof-reduction sends proofs to proofs of the same proposition).`,
    statement: String.raw`If $\Gamma \vdash M : A$ and $M \to_\beta M'$, then $\Gamma \vdash M' : A$.`,
    proof: String.raw`The proof rests on two structural facts about the typing rules of the **simply typed lambda calculus**, each proved by induction on derivations.

**Weakening.** If $\Gamma \vdash M : A$ and $\Gamma'$ extends $\Gamma$ with extra typed variables (not clashing with $\Gamma$), then $\Gamma' \vdash M : A$ — every rule application remains valid.

**Substitution lemma.** If $\Gamma,\, x : A \vdash M : B$ and $\Gamma \vdash N : A$, then $\Gamma \vdash M[x := N] : B$. Induct on the derivation of $\Gamma,\, x : A \vdash M : B$. If $M = x$, then $B = A$ and $M[x:=N] = N$ is typed by hypothesis; if $M$ is another variable, it is unaffected. If $M = \lambda y.\,M_0$ came from $(\mathrm{abs})$, the induction hypothesis types $M_0[x:=N]$ (using weakening to carry $N$'s typing under the binder), and $(\mathrm{abs})$ retypes the abstraction. If $M = M_1 M_2$ came from $(\mathrm{app})$, apply the induction hypothesis to each factor and reapply $(\mathrm{app})$.

**Main claim.** Induct on the derivation of $\Gamma \vdash M : A$, with cases on where the $\beta$-redex sits. The base redex case is $M = (\lambda x.\,P)\,Q \to_\beta P[x := Q]$: its typing must end in $(\mathrm{app})$ from $\Gamma \vdash \lambda x.\,P : C \to A$ and $\Gamma \vdash Q : C$, and the former ends in $(\mathrm{abs})$ from $\Gamma,\, x : C \vdash P : A$. The substitution lemma then gives $\Gamma \vdash P[x := Q] : A$. If instead the redex lies inside a subterm, the matching congruence case ($(\mathrm{abs})$ or $(\mathrm{app})$) applies the induction hypothesis to that subterm and rebuilds the same final rule, preserving the type. $\square$`,
  },
  {
    id: 'stlc-strong-normalization',
    label: 'STLC Normalization',
    title: 'Strong Normalization of STLC',
    kind: 'theorem',
    tags: ['Type Theory'],
    dependencies: ['simply-typed-lambda-calculus', 'type-preservation'],
    description: String.raw`The price of typing is paid back as termination: in the simply typed lambda calculus **every** reduction sequence is finite — no well-typed program loops. Equivalently, every typable term reduces to a (unique, by confluence) **normal form**. This is what makes STLC a *total* programming language rather than a Turing-complete one, and under Curry–Howard it is the statement that proof normalization in intuitionistic logic always terminates (cut elimination). The result needs more than induction on terms — naive structural induction fails because substitution can enlarge a term — and is proved by Tait's method of reducibility.`,
    statement: String.raw`Every typable term of the simply typed lambda calculus is **strongly normalizing**: there is no infinite sequence $M \to_\beta M_1 \to_\beta M_2 \to_\beta \cdots$ of $\beta$-reductions starting from it.`,
    proof: String.raw`By **Tait's reducibility** (the method of logical relations). The obstacle to a direct induction is the $(\mathrm{app})$ case: knowing $M$ and $N$ are strongly normalizing says nothing about $M\,N$, since contracting a redex in $M\,N$ may substitute $N$ and create new redexes. Tait's idea is to prove a *stronger*, type-indexed property by induction on types.

Write $\mathrm{SN}$ for the set of strongly normalizing terms. Define the **reducibility** predicate $\llbracket A \rrbracket$ on terms by recursion on the type $A$:
$$\llbracket \iota \rrbracket = \mathrm{SN} \quad (\iota \text{ a base type}), \qquad \llbracket A \to B \rrbracket = \{\,M : M\,N \in \llbracket B \rrbracket \text{ for every } N \in \llbracket A \rrbracket\,\}.$$
One proves simultaneously, by induction on $A$, three **CR (candidate of reducibility)** properties:
1. $\llbracket A \rrbracket \subseteq \mathrm{SN}$ (reducible terms terminate);
2. $\llbracket A \rrbracket$ is closed under reduction (if $M \in \llbracket A \rrbracket$ and $M \to_\beta M'$ then $M' \in \llbracket A \rrbracket$) — invoking **type preservation** so that $M'$ stays at type $A$;
3. (*neutrality*) if $M$ is neutral (a variable or application, not an abstraction) and every one-step reduct of $M$ is in $\llbracket A \rrbracket$, then $M \in \llbracket A \rrbracket$; in particular every variable is reducible.

The CR properties give a key **closure lemma**: if $M[x := N] \in \llbracket B \rrbracket$ for every $N \in \llbracket A \rrbracket$, then $\lambda x.\,M \in \llbracket A \to B \rrbracket$. Indeed for $N \in \llbracket A \rrbracket$ the redex $(\lambda x.\,M)\,N$ is neutral; by CR1 both $M$ and $N$ are in $\mathrm{SN}$, so an induction on the sum of their reduction lengths shows every one-step reduct of $(\lambda x.\,M)\,N$ lies in $\llbracket B \rrbracket$ (the contracted redex gives $M[x:=N] \in \llbracket B \rrbracket$ by hypothesis; inner reductions use CR2), whence $(\lambda x.\,M)\,N \in \llbracket B \rrbracket$ by CR3.

**Main lemma (reducibility of every typable term).** If $x_1 : A_1, \dots, x_n : A_n \vdash M : B$ and $N_i \in \llbracket A_i \rrbracket$ for each $i$, then $M[\vec x := \vec N] \in \llbracket B \rrbracket$. Induct on the typing derivation: the $(\mathrm{var})$ case is the assumption $N_i \in \llbracket A_i \rrbracket$; the $(\mathrm{app})$ case is immediate from the definition of $\llbracket A \to B \rrbracket$; the $(\mathrm{abs})$ case is exactly the closure lemma.

Taking each $N_i = x_i$ (reducible, by CR3 applied to variables) yields $M \in \llbracket B \rrbracket$ for every typable $M$, and CR1 gives $M \in \mathrm{SN}$. Hence every typable term is strongly normalizing. $\square$`,
  },

  // ── The Curry–Howard correspondence ─────────────────────────────────────────
  {
    id: 'curry-howard-correspondence',
    label: 'Curry–Howard',
    title: 'Curry–Howard Correspondence',
    kind: 'theorem',
    tags: ['Type Theory'],
    dependencies: ['simply-typed-lambda-calculus', 'sum-and-product-types', 'logical-connectives', 'stlc-strong-normalization', 'type-preservation'],
    description: String.raw`The **Curry–Howard correspondence** is the discovery that two seemingly different activities — proving theorems and writing programs — are *literally the same*. Read a type as a proposition and a term of that type as a proof of it: a function $A \to B$ is exactly a method turning proofs of $A$ into proofs of $B$, which is the constructive meaning of implication. Adding product and sum types matches conjunction and disjunction. Most strikingly, evaluating a program (normalizing a term) is the very same process as simplifying a proof (cut elimination). Intuitionistic logic and typed computation are two readings of one calculus — the conceptual foundation of every proof assistant.`,
    statement: String.raw`There is an isomorphism between the **simply typed lambda calculus** (with $\to$, products, and sums) and the **natural-deduction proof system for intuitionistic propositional logic** (with $\to$, $\wedge$, $\vee$), under the reading "types $=$ propositions, terms $=$ proofs." Precisely, reading each type as a propositional formula:
- typing derivations $\Gamma \vdash M : A$ correspond bijectively to natural-deduction proofs of $A$ from the assumptions in $\Gamma$, with the term $M$ recording the proof;
- the typing rules $(\mathrm{var})$, $(\mathrm{abs})$, $(\mathrm{app})$ are the rules assumption, $\to$-introduction, and $\to$-elimination, and similarly for the product/sum formers and $\wedge, \vee$;
- on the $\{\to, \wedge\}$ fragment $\beta$-reduction corresponds exactly to **detour elimination** (the term-level form of cut elimination), so $\beta$-normal terms are normal (cut-free) proofs; on the full $\{\to, \wedge, \vee\}$ system this correspondence holds for $\beta$-reduction *together with* the **commuting (permutative) conversions**, the disjunction case-analysis conversions having no plain $\beta$-counterpart, so a $\beta$-normal term need not yet be a normal proof.

Consequently a propositional formula $A$ is **intuitionistically provable** if and only if, read as a type, $A$ is **inhabited** (some closed term has type $A$).`,
    proof: String.raw`Translate types to formulas by reading the base type former and $\to$ as atoms and implication, $\times$ as $\wedge$, and $+$ as $\vee$. We exhibit the correspondence rule by rule and then match the dynamics.

**Derivations correspond.** Reading types as formulas over the **logical connectives** $\to, \wedge, \vee$, compare the typing rules of the **simply typed lambda calculus** (with the product/sum formers of **sum-and-product-types**) against the inference rules of intuitionistic natural deduction:
$$\frac{(x:A)\in\Gamma}{\Gamma \vdash x : A} \;\leftrightarrow\; \text{(assumption } A\text{)}, \quad \frac{\Gamma, x:A \vdash M:B}{\Gamma \vdash \lambda x.M : A\to B} \;\leftrightarrow\; \to\!I, \quad \frac{\Gamma \vdash M:A\to B \quad \Gamma \vdash N:A}{\Gamma \vdash M\,N:B} \;\leftrightarrow\; \to\!E.$$
The variable rule is "use an assumption"; abstraction discharges the assumption $A$ to conclude $A \to B$, exactly $\to$-introduction; application is $\to$-elimination (modus ponens). For the products, pairing $\langle M, N\rangle : A \times B$ from $M:A$ and $N:B$ is $\wedge$-introduction, and the projections $\pi_1, \pi_2$ are the two $\wedge$-eliminations; for the sums, the injections $\mathrm{inl}, \mathrm{inr}$ are $\vee$-introduction and the case-analysis eliminator is $\vee$-elimination. Reading a typing derivation bottom-up *is* building a natural-deduction proof, and the term annotation is a faithful, invertible record of the proof tree (a "proof term"). This defines a bijection between typing derivations of $\Gamma \vdash M : A$ and natural-deduction proofs of $A$ from $\Gamma$, by structural induction on derivations: each constructor on one side has a unique counterpart on the other.

**Dynamics correspond.** A natural-deduction *detour* is an introduction immediately followed by the matching elimination; normalization removes it. The principal such detour, eliminating $\to I$ followed by $\to E$, rewrites
$$\frac{\;\vdots\; }{\;A \to B\;}(\to\!I) \quad \frac{}{A} \quad\Longrightarrow_{\to E}\quad \text{(plug the proof of } A \text{ into the discharged slots)},$$
which on proof terms is precisely $(\lambda x.\,M)\,N \to_\beta M[x := N]$: substituting the argument's proof for the discharged assumption. For conjunction the product detour, $\pi_i\langle M_1, M_2\rangle \to M_i$, is again exactly the corresponding $\beta$-rule, so on the $\{\to, \wedge\}$ fragment "remove a detour" on proofs and $\beta$-reduction on terms are literally the same relation under the bijection. Disjunction is subtler: the $\vee$-elimination detour case-of-injection, $\mathrm{case}\,(\mathrm{inl}\,M)\,\{x.U \mid y.V\} \to U[x := M]$, is one $\beta$-rule, but full proof normalization for $\vee$ also requires the **commuting (permutative) conversions**, which push an eliminator past a $\mathrm{case}$ and have no counterpart among the plain $\beta$-rules; they are needed for normal proofs to enjoy the subformula property. So on the full $\{\to, \wedge, \vee\}$ system the dynamics correspond under "$\beta$-reduction *together with* the commuting conversions," not $\beta$-reduction alone. In every case **type preservation** keeps the conclusion fixed. The typed calculus is **strongly normalizing** — proved for the $\to$-fragment in the cited node, and extended to products and sums by the same Tait reducibility method (adding clauses for $\times$ and $+$) — so every proof reduces to a normal (detour-free) form: the term-calculus incarnation of the normalization theorem for intuitionistic natural deduction.

**Provability $=$ inhabitation.** A closed proof term $M$ with $\vdash M : A$ is, by the bijection, a natural-deduction proof of $A$ from no assumptions, so $A$ is intuitionistically provable; conversely any such proof yields, by the same bijection, a closed inhabitant of the type $A$. Hence $A$ is intuitionistically provable iff $A$ is inhabited. $\square$`,
  },

  // ── Type formers ────────────────────────────────────────────────────────────
  {
    id: 'sum-and-product-types',
    label: 'Sum & Product Types',
    title: 'Sum & Product Types',
    kind: 'definition',
    tags: ['Type Theory'],
    dependencies: ['simply-typed-lambda-calculus'],
    description: String.raw`**Product** and **sum types** are the type-theoretic conjunction and disjunction. A product $A \times B$ packages a value of each, retrieved by the projections $\pi_1, \pi_2$; a sum $A + B$ holds a value of *one* side, tagged by the injections $\mathrm{inl}, \mathrm{inr}$ and consumed by case analysis. They are characterized by *universal properties*: the product is the way to map *into* a pair of types, the sum the way to map *out of* a choice of types. Closed under recursion they become the **algebraic data types** of functional languages, and with the function type they form the core type formers.`,
    definition: String.raw`Extend the simply typed lambda calculus with two type formers and their rules.

**Product** $A \times B$. Introduction pairs and eliminations project:
$$\frac{\Gamma \vdash M : A \quad \Gamma \vdash N : B}{\Gamma \vdash \langle M, N\rangle : A \times B}, \qquad \frac{\Gamma \vdash P : A \times B}{\Gamma \vdash \pi_1 P : A}, \qquad \frac{\Gamma \vdash P : A \times B}{\Gamma \vdash \pi_2 P : B},$$
with computation rules $\pi_1\langle M, N\rangle \to M$ and $\pi_2\langle M, N\rangle \to N$.

**Sum** $A + B$. Introduction injects and elimination does case analysis:
$$\frac{\Gamma \vdash M : A}{\Gamma \vdash \mathrm{inl}\,M : A + B}, \qquad \frac{\Gamma \vdash N : B}{\Gamma \vdash \mathrm{inr}\,N : A + B}, \qquad \frac{\Gamma \vdash P : A + B \quad \Gamma, x:A \vdash U : C \quad \Gamma, y:B \vdash V : C}{\Gamma \vdash \mathrm{case}\,P\,\{x.U \mid y.V\} : C},$$
with $\mathrm{case}\,(\mathrm{inl}\,M)\,\{x.U \mid y.V\} \to U[x := M]$ and symmetrically for $\mathrm{inr}$. A nullary product is the **unit type** $\mathbf{1}$ (the terminal type, with sole term $\langle\rangle$) and a nullary sum is the **empty type** $\mathbf{0}$ (the initial type, with the eliminator $\mathrm{absurd}$).`,
  },
  {
    id: 'polymorphism',
    label: 'Polymorphism',
    title: 'Parametric Polymorphism (System F)',
    kind: 'definition',
    tags: ['Type Theory'],
    dependencies: ['simply-typed-lambda-calculus', 'quantifiers'],
    description: String.raw`A single algorithm — say "return the input unchanged," or "reverse a list" — should work at *every* type without rewriting. **Parametric polymorphism** captures this by quantifying over types: the identity $\Lambda\alpha.\,\lambda x{:}\alpha.\,x$ has type $\forall \alpha.\,\alpha \to \alpha$, and is instantiated at a type by type application. "Parametric" means the term must behave *uniformly* — it cannot inspect the type it runs at — which forces strong uniformity constraints (Reynolds's parametricity, the "free theorems"). Formalized as **System F**, it corresponds under Curry–Howard to second-order intuitionistic propositional logic and underlies the generics of modern programming languages.`,
    definition: String.raw`**System F** (the polymorphic, or second-order, lambda calculus) extends the simply typed lambda calculus with **type variables** $\alpha$ and a universally quantified type former. Types are
$$A, B ::= \alpha \;\mid\; A \to B \;\mid\; \forall \alpha.\,A,$$
and terms gain **type abstraction** $\Lambda\alpha.\,M$ and **type application** $M\,[A]$, with rules
$$\frac{\Gamma \vdash M : A \quad (\alpha \text{ not free in } \Gamma)}{\Gamma \vdash \Lambda\alpha.\,M : \forall \alpha.\,A}, \qquad \frac{\Gamma \vdash M : \forall \alpha.\,A}{\Gamma \vdash M\,[B] : A[\alpha := B]},$$
and the computation rule $(\Lambda\alpha.\,M)\,[B] \to_\beta M[\alpha := B]$. The side condition on type abstraction (mirroring the proviso for the $\forall$-introduction of the **quantifiers**) is what makes the quantification genuinely universal. System F is also strongly normalizing, though its proof requires impredicative reducibility candidates.`,
  },

  // ── Dependent types ─────────────────────────────────────────────────────────
  {
    id: 'dependent-type',
    label: 'Dependent Type',
    title: 'Dependent Type',
    kind: 'definition',
    tags: ['Type Theory'],
    dependencies: ['simply-typed-lambda-calculus'],
    description: String.raw`In the simple and polymorphic calculi, types may depend on *types* but never on ordinary *values*. A **dependent type** lifts this restriction: a type may vary with a term, like the type $\mathrm{Vec}(A, n)$ of length-$n$ vectors indexed by $n : \mathbb{N}$. Such families let a type carry a precise specification ("a vector of length exactly $n$," "a proof that $x = y$"), so that type-checking *is* specification-checking. Dependency generalizes the function and product types to the $\Pi$- and $\Sigma$-types and is the decisive step from a programming type system toward a foundation able to *state and prove* theorems.`,
    definition: String.raw`A **type family** over a type $A$ is a function $B$ assigning to each $a : A$ a type $B(a)$; formally it is a judgment $x : A \vdash B(x)\ \mathrm{type}$, derived in a context. A **dependent type** is a type $B(a)$ that is an instance of such a family — a type whose very formation depends on a term $a : A$, not merely on another type. The basic judgments of a dependent type theory are therefore relativized to contexts: $\Gamma\ \mathrm{ctx}$ (well-formed context), $\Gamma \vdash A\ \mathrm{type}$ ($A$ is a type in $\Gamma$), $\Gamma \vdash a : A$ ($a$ inhabits $A$), together with **definitional (judgmental) equality** $\Gamma \vdash a \equiv a' : A$ and $\Gamma \vdash A \equiv A'\ \mathrm{type}$, the latter enforced by the **conversion rule**: if $\Gamma \vdash a : A$ and $\Gamma \vdash A \equiv B\ \mathrm{type}$ then $\Gamma \vdash a : B$.`,
  },
  {
    id: 'pi-and-sigma-types',
    label: 'Π- & Σ-Types',
    title: 'Dependent Function & Pair Types',
    kind: 'definition',
    tags: ['Type Theory'],
    dependencies: ['dependent-type', 'quantifiers', 'sum-and-product-types'],
    description: String.raw`The two basic dependent type formers generalize the function and product. The **dependent function type** $\prod_{x : A} B(x)$ collects functions whose *result type* depends on the argument — given $a : A$, the output lies in $B(a)$. The **dependent pair type** $\sum_{x : A} B(x)$ collects pairs $(a, b)$ where the *second component's type* $B(a)$ depends on the first. When $B$ is constant they degenerate to $A \to B$ and $A \times B$. Under Curry–Howard they are the **universal** and **existential quantifiers**: $\prod_{x:A} B(x)$ reads "for all $x:A$, $B(x)$," and $\sum_{x:A} B(x)$ reads "there exists $x:A$ with $B(x)$," the pair witnessing the existential constructively.`,
    definition: String.raw`Let $A$ be a type and $x : A \vdash B(x)\ \mathrm{type}$ a family.

**Π-type (dependent function).** Formation $\Gamma \vdash \prod_{x:A} B(x)\ \mathrm{type}$; introduction by abstraction $\dfrac{\Gamma, x:A \vdash b : B(x)}{\Gamma \vdash \lambda x.\,b : \prod_{x:A} B(x)}$; elimination by application $\dfrac{\Gamma \vdash f : \prod_{x:A} B(x) \quad \Gamma \vdash a : A}{\Gamma \vdash f\,a : B(a)}$; computation $(\lambda x.\,b)\,a \equiv b[x := a]$. The non-dependent case ($B$ constant) is the ordinary function type $A \to B$.

**Σ-type (dependent pair).** Formation $\Gamma \vdash \sum_{x:A} B(x)\ \mathrm{type}$; introduction by pairing $\dfrac{\Gamma \vdash a : A \quad \Gamma \vdash b : B(a)}{\Gamma \vdash (a, b) : \sum_{x:A} B(x)}$; elimination by the projections $\pi_1 : \sum_{x:A} B(x) \to A$ and $\pi_2 : \prod_{p : \sum_{x:A} B(x)} B(\pi_1 p)$ (itself dependent), with $\pi_1(a,b) \equiv a$ and $\pi_2(a,b) \equiv b$. The non-dependent case is the product $A \times B$, so the Σ-type generalizes the product among the **sum-and-product** formers, while reading as the existential quantifier of the **quantifiers**.`,
  },
  {
    id: 'inductive-type',
    label: 'Inductive Type',
    title: 'Inductive Type',
    kind: 'definition',
    tags: ['Type Theory'],
    dependencies: ['dependent-type', 'natural-numbers'],
    description: String.raw`An **inductive type** is generated *freely* by a finite list of **constructors** — the naturals from $0$ and $\mathrm{succ}$, lists from $\mathrm{nil}$ and $\mathrm{cons}$, binary trees from a leaf and a node former. "Freely" means its elements are exactly the finite expressions built from the constructors, with no further identifications. Each inductive type comes with an **induction principle** (a dependent eliminator, or *recursor*): to define a function on it, or to prove a property of all its elements, it suffices to handle each constructor, assuming the result already for the constructor's recursive arguments. Inductive types are how *data* and *proof by induction* are simultaneously expressed in type theory.`,
    definition: String.raw`An **inductive type** $W$ is specified by a list of **constructors**, each of the form $c : (\text{args}) \to W$ where the arguments may include previous data and **recursive** occurrences of $W$ (subject to a *strict positivity* condition: $W$ may not occur to the left of an arrow inside an argument, which guarantees the type is well-founded). $W$ is the type freely generated by these constructors. Its defining property is the **dependent eliminator** (induction principle): for any family $x : W \vdash P(x)\ \mathrm{type}$, given for each constructor $c$ a "method" producing $P(c(\dots))$ from the arguments together with $P$ applied to the recursive arguments, there is a function $\mathrm{ind}_W : \prod_{x:W} P(x)$ satisfying the **computation rule** $\mathrm{ind}_W(c(\dots)) \equiv (\text{the method for } c)$. For example $\mathbb{N}$ has constructors $0 : \mathbb{N}$ and $\mathrm{succ} : \mathbb{N} \to \mathbb{N}$, and its eliminator is exactly mathematical induction; this reproduces the recursion of the von Neumann **natural numbers** as a type former.`,
  },
  {
    id: 'identity-type',
    label: 'Identity Type',
    title: 'Identity Type',
    kind: 'definition',
    tags: ['Type Theory'],
    dependencies: ['dependent-type', 'inductive-type'],
    description: String.raw`How should "$a$ equals $b$" be expressed when propositions are types? Martin-Löf's answer is the **identity type** $\mathrm{Id}_A(a, b)$, written $a =_A b$: a type whose *terms are proofs* that $a$ and $b$ are equal. It has a single constructor, reflexivity $\mathrm{refl}_a : a =_A a$, and its eliminator — path induction (the **J rule**) — says, roughly, that to prove something about an arbitrary equality proof it suffices to handle the case $\mathrm{refl}$. Treating equality as an inductive *type* rather than a primitive proposition is what gives Martin-Löf type theory much of its power, and — because $a =_A b$ can itself contain non-trivial structure — opens the door to the homotopical interpretation.`,
    definition: String.raw`For a type $A$ and terms $a, b : A$, the **identity type** $a =_A b$ is the inductive family generated by the single constructor
$$\mathrm{refl}_a : a =_A a \qquad (a : A).$$
Its eliminator is **path induction** ($\mathsf{J}$): given a family $C(x, y, p)$ for $x, y : A$ and $p : x =_A y$, and a term $d : \prod_{x:A} C(x, x, \mathrm{refl}_x)$, there is
$$\mathsf{J}(d) : \prod_{x, y : A}\;\prod_{p : x =_A y} C(x, y, p), \qquad \mathsf{J}(d)(a, a, \mathrm{refl}_a) \equiv d(a).$$
This is exactly the eliminator one obtains by reading $=_A$ as an **inductive type** with the lone constructor $\mathrm{refl}$. From $\mathsf{J}$ one derives that equality is an equivalence relation and a congruence (substitutivity: $p : a =_A b$ transports $C(a)$ to $C(b)$).`,
  },
  {
    id: 'universe-type',
    label: 'Universe',
    title: 'Universe (Type of Types)',
    kind: 'definition',
    tags: ['Type Theory'],
    dependencies: ['dependent-type'],
    description: String.raw`To define types by recursion, to quantify over all types, or to treat "being a type" as data, a type theory needs a type whose *elements are types*: a **universe** $\mathcal{U}$, with $A : \mathcal{U}$ meaning "$A$ is a (small) type." A single all-encompassing type of all types, $\mathcal{U} : \mathcal{U}$, is inconsistent — Girard's paradox encodes a type-theoretic Russell/Burali-Forti argument and produces a closed term of the empty type. The fix is to **stratify** universes into a hierarchy $\mathcal{U}_0 : \mathcal{U}_1 : \mathcal{U}_2 : \cdots$, each a member of the next; taken **cumulative**, a type in $\mathcal{U}_i$ also lies in $\mathcal{U}_{i+1}$. Universes make polymorphism and large constructions expressible internally without collapsing consistency.`,
    definition: String.raw`A **universe** is a type $\mathcal{U}$ together with a family $x : \mathcal{U} \vdash \mathrm{El}(x)\ \mathrm{type}$ decoding each element to the type it names (often left implicit, writing $A : \mathcal{U}$ for both the code and the type $\mathrm{El}(A)$), closed under the type formers — e.g. if $A : \mathcal{U}$ and $x : \mathrm{El}(A) \vdash B(x) : \mathcal{U}$ then $\prod_{x:A} B(x) : \mathcal{U}$ and $\sum_{x:A} B(x) : \mathcal{U}$. To avoid the inconsistency of $\mathcal{U} : \mathcal{U}$ (Girard's paradox), one posits a **cumulative hierarchy** of universes
$$\mathcal{U}_0 : \mathcal{U}_1 : \mathcal{U}_2 : \cdots, \qquad (A : \mathcal{U}_i) \Rightarrow (A : \mathcal{U}_{i+1}),$$
with each $\mathcal{U}_i$ closed under the formers and $\mathcal{U}_i$ itself an element of $\mathcal{U}_{i+1}$ but not of $\mathcal{U}_i$. A type is **small** (relative to a level) when it has a code in the corresponding universe.`,
  },

  // ── Foundational theories ───────────────────────────────────────────────────
  {
    id: 'martin-lof-type-theory',
    label: 'Martin-Löf Type Theory',
    title: 'Martin-Löf Type Theory',
    kind: 'definition',
    tags: ['Type Theory'],
    dependencies: ['dependent-type', 'pi-and-sigma-types', 'identity-type', 'inductive-type', 'universe-type'],
    description: String.raw`**Martin-Löf type theory** (MLTT) is a constructive *foundation for mathematics* assembled from the dependent type formers: $\Pi$- and $\Sigma$-types, inductive types (giving $\mathbb{N}$, sums, the unit and empty types), identity types, and a cumulative universe hierarchy. Under Curry–Howard, propositions are types and proofs are terms, so a single calculus is at once a total functional programming language and a logic. Crucially it is **predicative** (no impredicative universe of propositions) and constructive (no excluded middle by default). It is the theory implemented by proof assistants such as Agda, and the immediate predecessor of homotopy type theory.`,
    definition: String.raw`**Martin-Löf type theory** is the dependent type theory whose judgments are the context/type/term/equality judgments of the **dependent-type** framework, with the **conversion rule**, and whose type formers are:
- **dependent functions** $\prod_{x:A} B(x)$ and **dependent pairs** $\sum_{x:A} B(x)$ (the **Π- and Σ-types**);
- **inductive types**: the empty type $\mathbf{0}$, unit $\mathbf{1}$, booleans $\mathbf{2}$, natural numbers $\mathbb{N}$, sums $A + B$, and well-founded ($W$-)types — instances of the general **inductive-type** scheme;
- **identity types** $a =_A b$ with reflexivity and path induction $\mathsf{J}$;
- a cumulative **universe** hierarchy $\mathcal{U}_0 : \mathcal{U}_1 : \cdots$ closed under all the above.
Each former is given by formation, introduction, elimination, and computation rules in the standard pattern. The theory is **predicative** ($\prod$ over a universe lands one level up) and admits no axioms beyond these rules; logical operations are recovered by Curry–Howard ($\to, \times, +, \prod, \sum$ for $\to, \wedge, \vee, \forall, \exists$).`,
  },
  {
    id: 'calculus-of-constructions',
    label: 'Calculus of Constructions',
    title: 'Calculus of Constructions',
    kind: 'definition',
    tags: ['Type Theory'],
    dependencies: ['dependent-type', 'polymorphism', 'inductive-type'],
    description: String.raw`The **calculus of constructions** (CoC) combines dependent types with the full **polymorphism** of System F and with **type operators** (types depending on types), sitting at the apex of Barendregt's lambda cube where all three dimensions of abstraction are present. It is a higher-order constructive logic with an **impredicative** universe $\mathrm{Prop}$ of propositions — propositions may quantify over all propositions, allowing the connectives to be *defined* rather than postulated. Extended with primitive **inductive types** it becomes the **Calculus of Inductive Constructions** (CIC), the theory underlying the Coq/Rocq proof assistant and a powerful setting for large-scale formalized mathematics.`,
    definition: String.raw`The **calculus of constructions** is a *pure type system* with two sorts, $\mathrm{Prop}$ (the impredicative universe of propositions/small types) and $\mathrm{Type}$, related by $\mathrm{Prop} : \mathrm{Type}$, and a single dependent-product former $\prod_{x:A} B$ governed by the rules $(s_1, s_2)$ for all pairs of sorts $s_1, s_2 \in \{\mathrm{Prop}, \mathrm{Type}\}$. The four rules realize, respectively: simple functions $(\mathrm{Prop}, \mathrm{Prop})$, polymorphism / impredicative quantification $(\mathrm{Type}, \mathrm{Prop})$ — so $\prod_{A:\mathrm{Prop}} \dots : \mathrm{Prop}$, the **impredicativity** — type operators $(\mathrm{Type}, \mathrm{Type})$, and dependent types $(\mathrm{Prop}, \mathrm{Type})$. It generalizes **System F** (which uses only $(\mathrm{Prop},\mathrm{Prop})$ and $(\mathrm{Type},\mathrm{Prop})$) by adding dependency. The **Calculus of Inductive Constructions** augments it with the **inductive-type** scheme and a predicative hierarchy $\mathrm{Type}_0 : \mathrm{Type}_1 : \cdots$ above $\mathrm{Prop}$.`,
  },
  {
    id: 'homotopy-type-theory',
    label: 'Homotopy Type Theory',
    title: 'Homotopy Type Theory',
    kind: 'definition',
    tags: ['Type Theory'],
    dependencies: ['martin-lof-type-theory', 'identity-type', 'type-equivalence', 'univalence-axiom', 'higher-inductive-type'],
    description: String.raw`**Homotopy type theory** (HoTT) is the discovery of a homotopical meaning hidden in Martin-Löf's identity types: read a type as a *space*, its terms as *points*, and a term of $a =_A b$ as a *path* from $a$ to $b$. Then identity proofs between paths are homotopies, and the whole tower $a =_A b$, $p =_{(a=b)} q$, $\dots$ records the higher homotopy structure. On this reading two new principles become natural: the **univalence axiom**, which makes *equivalent types equal* (so $(A \simeq B) \simeq (A = B)$), and **higher inductive types**, which build spaces — circles, spheres, quotients — by giving constructors for points *and for paths*. Together they yield a foundation in which every construction is automatically invariant under equivalence.`,
    definition: String.raw`**Homotopy type theory** is **Martin-Löf type theory** under the *homotopical interpretation*, in which each type is a space (an $\infty$-groupoid), terms are points, and the **identity type** $a =_A b$ is the type of paths $a \rightsquigarrow b$; the iterated identity types $p =_{(a=_A b)} q$ give higher paths. Define a function $f : A \to B$ to be an **equivalence**, $A \simeq B$, when it has a suitable two-sided inverse up to homotopy (equivalently, all its homotopy fibers are contractible). HoTT extends MLTT with two principles:
- the **univalence axiom**: the canonical map $(A =_{\mathcal{U}} B) \to (A \simeq B)$ is itself an equivalence, so identity of types *is* equivalence;
- **higher inductive types**: inductive types whose constructors may produce *paths* (and higher paths), not only points, presenting spaces and quotients directly.
The classifications of types by truncation level — (-1)-types (mere propositions), 0-types (sets), and higher — organize logic and set-level mathematics inside the theory.`,
  },
  {
    id: 'type-equivalence',
    label: 'Type Equivalence',
    title: 'Equivalence of Types',
    kind: 'definition',
    tags: ['Type Theory'],
    dependencies: ['pi-and-sigma-types', 'identity-type'],
    description: String.raw`When are two types "the same"? Set-theoretically the answer is *bijection*; in type theory, where the identity type $a =_A b$ may carry structure, the right notion is **equivalence** $A \simeq B$ — a function with a two-sided inverse *up to homotopy*. Naively "$f$ has an inverse" ($\sum_{g} (g \circ f \sim \mathrm{id}) \times (f \circ g \sim \mathrm{id})$) is the correct *underlying* idea but a badly behaved predicate (it can hold in inequivalent ways). The standard fix is to package invertibility as a **proposition**: either as a *bi-invertible* map (separate left and right inverses) or via the *contractible-fibers* condition. Type equivalence is the foundational notion of sameness in homotopy type theory and the very thing the univalence axiom identifies with equality of types.`,
    definition: String.raw`Let $A, B$ be types. For $f : A \to B$ and $b : B$, the **fiber** of $f$ over $b$ is $\mathrm{fib}_f(b) :\equiv \sum_{a : A} (f(a) =_B b)$. A type $X$ is **contractible** if $\mathrm{isContr}(X) :\equiv \sum_{x_0 : X} \prod_{x : X} (x_0 =_X x)$ is inhabited (it has a center to which everything is equal). Define $f$ to be an **equivalence** by
$$\mathrm{isEquiv}(f) :\equiv \prod_{b : B} \mathrm{isContr}\!\big(\mathrm{fib}_f(b)\big),$$
i.e. every fiber is contractible. The type of equivalences from $A$ to $B$ is then $A \simeq B :\equiv \sum_{f : A \to B} \mathrm{isEquiv}(f)$. A homotopy $g \sim h$ between $g, h : \prod_{x:A} P(x)$ is the dependent-function type $\prod_{x:A} (g(x) =_{P(x)} h(x))$; one shows $\mathrm{isEquiv}(f)$ is logically equivalent to the **bi-invertibility** condition $\big(\sum_{g : B \to A}(g \circ f \sim \mathrm{id}_A)\big) \times \big(\sum_{h : B \to A}(f \circ h \sim \mathrm{id}_B)\big)$, and both are *mere propositions* (any two of their inhabitants are equal), unlike the naive "quasi-inverse" datum $\sum_{g}(g \circ f \sim \mathrm{id}) \times (f \circ g \sim \mathrm{id})$. The identity function is an equivalence, so $\mathrm{refl}$ yields the **identity equivalence** $\mathrm{id} : A \simeq A$.`,
  },
  {
    id: 'univalence-axiom',
    label: 'Univalence',
    title: 'Univalence Axiom',
    kind: 'axiom',
    tags: ['Type Theory'],
    dependencies: ['type-equivalence', 'identity-type', 'universe-type'],
    description: String.raw`Mathematicians routinely treat isomorphic structures as the same yet must, in set-based foundations, smuggle this in by hand. The **univalence axiom** of Voevodsky internalizes it: for types $A, B$ in a universe, *being equal is being equivalent*. There is always a canonical map from an equality $A = B$ to an equivalence $A \simeq B$ (transport along the path); univalence asserts this map is itself an equivalence. The consequence is that any property expressible in type theory is automatically transportable across equivalences — a precise, provable "principle of structure invariance" — at the cost of giving up the principle that all equality proofs are equal (univalence is incompatible with uniqueness of identity proofs at the universe level).`,
    statement: String.raw`For any universe $\mathcal{U}$ and types $A, B : \mathcal{U}$, the canonical function
$$\mathrm{idtoeqv} : (A =_{\mathcal{U}} B) \;\longrightarrow\; (A \simeq B),$$
defined by path induction sending $\mathrm{refl}_A$ to the identity equivalence, is itself an equivalence. Hence $(A =_{\mathcal{U}} B) \simeq (A \simeq B)$: identity of types is equivalent to equivalence of types.`,
  },
  {
    id: 'higher-inductive-type',
    label: 'Higher Inductive Type',
    title: 'Higher Inductive Type',
    kind: 'definition',
    tags: ['Type Theory'],
    dependencies: ['inductive-type', 'identity-type'],
    description: String.raw`An ordinary inductive type is freely generated by constructors for its *points*. A **higher inductive type** (HIT) goes further: its constructors may also generate *paths* — elements of identity types — and even higher paths. This lets one build genuine topological spaces and quotients directly inside type theory. The **circle** $S^1$, for instance, is generated by one point $\mathrm{base}$ and one path $\mathrm{loop} : \mathrm{base} = \mathrm{base}$; the eliminator then proves that its loop space is $\mathbb{Z}$, recovering the fundamental group $\pi_1(S^1)$ synthetically. Quotients, truncations, and pushouts are all HITs, making homotopy theory expressible without point-set topology.`,
    definition: String.raw`A **higher inductive type** is an inductive type whose specification lists **point constructors** (producing elements of the type, as for an ordinary **inductive-type**) *and* **path constructors** (producing elements of the **identity type** of the type being defined), and possibly higher path constructors. As with ordinary inductive types it is characterized by a dependent eliminator: to map out of (or prove a family over) the HIT, one supplies data for each point constructor *and*, for each path constructor, a path in the target lying over it (a $\mathrm{transport}$/$\mathrm{apd}$ condition). For example the circle $S^1$ is the HIT with one point constructor $\mathrm{base} : S^1$ and one path constructor $\mathrm{loop} : \mathrm{base} =_{S^1} \mathrm{base}$; its recursor sends $(b, \ell)$ with $b : X$, $\ell : b = b$ to a map $S^1 \to X$ taking $\mathrm{base} \mapsto b$ and $\mathrm{loop} \mapsto \ell$.`,
  },
]
