import type { MathNode } from '../types'

export const UNIVERSAL_ALGEBRA_NODES: MathNode[] = [
  // ── Structures & substructures ─────────────────────────────────────────────
  {
    id: 'algebraic-signature',
    label: 'Algebra & Signature',
    title: 'Signature & Algebraic Structure',
    kind: 'definition',
    tags: ['Universal Algebra'],
    dependencies: ['binary-operation', 'function', 'cartesian-product', 'natural-numbers'],
    description: String.raw`Groups, rings, lattices, and vector spaces all share a common shape: a set carrying some finitary operations subject to laws. Universal algebra studies that shape directly. A **signature** is a bare list of operation symbols, each tagged with an *arity* (how many inputs it takes); an **algebra** of that signature is a set together with one concrete operation for each symbol. Stripping away the laws first — they reappear later as *identities* — isolates the purely structural skeleton, so that one theory speaks at once about every "algebraic" structure built from operations. A binary operation is the arity-$2$ case; a $0$-ary operation is a distinguished constant such as a group identity.`,
    definition: String.raw`A **signature** (or *type*) is a set $\Sigma$ of **operation symbols** together with an **arity** function $\mathrm{ar} : \Sigma \to \mathbb{N}$. An **algebra** of signature $\Sigma$ is a pair $\mathbf{A} = (A, (f^{\mathbf A})_{f \in \Sigma})$ where $A$ is a nonempty set, the **carrier**, and each $f \in \Sigma$ of arity $n = \mathrm{ar}(f)$ is interpreted as an operation $f^{\mathbf A} : A^n \to A$. An arity-$0$ symbol is a **constant**, interpreted as a chosen element $f^{\mathbf A} \in A$ (a map $A^0 \to A$ from the one-point set $A^0$); an arity-$2$ symbol is a **binary operation** $A \times A \to A$. A group is the algebra of signature $\{\cdot, {}^{-1}, e\}$ with arities $2, 1, 0$.`,
  },
  {
    id: 'subalgebra',
    label: 'Subalgebra',
    title: 'Subalgebra',
    kind: 'definition',
    tags: ['Universal Algebra'],
    dependencies: ['algebraic-signature', 'subset'],
    description: String.raw`A **subalgebra** is a subset of an algebra that is *closed* under all of its operations: feeding elements of the subset into any operation never escapes the subset, and every constant already lies inside. Closure is exactly what is needed for the operations to restrict and make the subset an algebra in its own right. Subgroups, subrings, and sublattices are the familiar instances. Closure is preserved by arbitrary intersection, so each subset generates a smallest subalgebra containing it.`,
    definition: String.raw`Let $\mathbf{A} = (A, (f^{\mathbf A})_{f \in \Sigma})$ be an algebra. A subset $B \subseteq A$ is **closed** under $f \in \Sigma$ of arity $n$ if $f^{\mathbf A}(b_1, \dots, b_n) \in B$ whenever $b_1, \dots, b_n \in B$ (for $n = 0$ this requires the constant $f^{\mathbf A} \in B$). If $B$ is nonempty and closed under every $f \in \Sigma$, the **subalgebra** $\mathbf{B} = (B, (f^{\mathbf B})_{f \in \Sigma})$ has carrier $B$ with each operation the restriction $f^{\mathbf B} := f^{\mathbf A}\!\restriction_{B^n}$; we write $\mathbf{B} \le \mathbf{A}$. For a subset $X \subseteq A$ such that $X \neq \varnothing$ or $\Sigma$ contains a constant, the **subalgebra generated by $X$**, written $\langle X\rangle$, is the intersection of all subalgebras containing $X$. (Without that proviso the intersection can be empty — e.g. for the magma signature $\Sigma = \{\cdot\}$ with $\cdot$ a single binary operation and $X = \varnothing$ — and so fails to be a subalgebra; one then either restricts to this case or drops the nonemptiness requirement on subalgebras.)`,
    proof: String.raw`**Under the proviso ($X \neq \varnothing$ or $\Sigma$ has a constant), $\langle X\rangle$ is the least subalgebra containing $X$.** The intersection $C = \bigcap\{B : X \subseteq B \le \mathbf A\}$ (taken over a nonempty family, since $A$ itself is such a $B$) is closed under each $f \in \Sigma$: if $c_1, \dots, c_n \in C$ then $c_1, \dots, c_n$ lie in every $B$ in the family, so $f^{\mathbf A}(c_1, \dots, c_n) \in B$ for each such $B$ as each is **closed**, hence the value lies in their intersection $C$; constants lie in every $B$, hence in $C$. It remains to see $C \neq \varnothing$, which is exactly where the proviso enters: if $X \neq \varnothing$ then $X \subseteq C$ makes $C$ nonempty; if instead $\Sigma$ has a constant $c$ then $c^{\mathbf A}$ lies in every $B$ in the family, hence in $C$. (Were $X = \varnothing$ and $\Sigma$ constant-free, $C$ could be empty, as in the magma example, and the claim would fail.) Thus $C$ is a nonempty closed set, i.e. a **subalgebra** containing $X$, and by construction it is contained in every subalgebra containing $X$. $\square$`,
  },
  {
    id: 'algebra-homomorphism',
    label: 'Homomorphism',
    title: 'Homomorphism of Algebras',
    kind: 'definition',
    tags: ['Universal Algebra'],
    dependencies: ['algebraic-signature', 'subalgebra', 'function-composition', 'bijection', 'inverse-function'],
    description: String.raw`The structure-preserving maps between algebras of a fixed signature are the **homomorphisms**: maps that commute with every operation, so that operating then mapping agrees with mapping then operating. Group, ring, and lattice homomorphisms are all special cases. A homomorphism carries subalgebras to subalgebras, the image of the whole algebra is a subalgebra of the target, and a bijective homomorphism whose inverse is also a homomorphism is an **isomorphism**, the precise sense in which two algebras are "the same."`,
    definition: String.raw`Let $\mathbf{A}, \mathbf{B}$ be algebras of the same signature $\Sigma$. A map $h : A \to B$ is a **homomorphism**, written $h : \mathbf{A} \to \mathbf{B}$, if for every $f \in \Sigma$ of arity $n$ and all $a_1, \dots, a_n \in A$,
$$h\bigl(f^{\mathbf A}(a_1, \dots, a_n)\bigr) = f^{\mathbf B}\bigl(h(a_1), \dots, h(a_n)\bigr),$$
where for a constant ($n = 0$) this reads $h(f^{\mathbf A}) = f^{\mathbf B}$. A homomorphism is an **isomorphism** if it is bijective and $h^{-1}$ is also a homomorphism; an **embedding** if it is injective.`,
    proof: String.raw`**The image $h(\mathbf A)$ is a subalgebra of $\mathbf B$, and a bijective homomorphism is an isomorphism.** For closure of $h(A)$: given $h(a_1), \dots, h(a_n) \in h(A)$, the homomorphism law gives $f^{\mathbf B}(h(a_1), \dots, h(a_n)) = h(f^{\mathbf A}(a_1, \dots, a_n)) \in h(A)$, and each constant $f^{\mathbf B} = h(f^{\mathbf A}) \in h(A)$; since $A$ is nonempty so is $h(A)$, hence $h(A)$ is a **subalgebra** by definition. Now suppose $h$ is a bijective homomorphism with **inverse** $g = h^{-1}$, so $h \circ g = \mathrm{id}_B$ and $g \circ h = \mathrm{id}_A$. For any $b_1, \dots, b_n \in B$ put $a_i = g(b_i)$; then $h(a_i) = h(g(b_i)) = b_i$ by $h \circ g = \mathrm{id}_B$, so $g\bigl(f^{\mathbf B}(b_1, \dots, b_n)\bigr) = g\bigl(f^{\mathbf B}(h(a_1), \dots, h(a_n))\bigr) = g\bigl(h(f^{\mathbf A}(a_1, \dots, a_n))\bigr) = f^{\mathbf A}(g(b_1), \dots, g(b_n))$, the second equality by $h$'s law and the last by $g \circ h = \mathrm{id}_A$ (**function composition**). So $g$ is a homomorphism and $h$ is an isomorphism. $\square$`,
  },

  // ── Congruences & quotients ────────────────────────────────────────────────
  {
    id: 'congruence-relation',
    label: 'Congruence',
    title: 'Congruence Relation',
    kind: 'definition',
    tags: ['Universal Algebra'],
    dependencies: ['algebraic-signature', 'equivalence-relation', 'equivalence-class', 'algebra-homomorphism'],
    description: String.raw`A **congruence** is an equivalence relation on an algebra that is also *compatible* with every operation: replacing arguments by equivalent ones leaves the output equivalent. This is exactly the abstract condition that lets the operations descend to the equivalence classes. The notion unifies several familiar devices — congruence modulo $n$ on $\mathbb{Z}$, normal subgroups (as the relation $a \sim b \iff ab^{-1} \in N$), and ideals (as $a \sim b \iff a - b \in I$) all arise as congruences — and the congruences of an algebra, ordered by inclusion, form a complete lattice whose structure controls the algebra's quotients.`,
    definition: String.raw`A **congruence** on an algebra $\mathbf{A}$ of signature $\Sigma$ is an **equivalence relation** $\theta \subseteq A \times A$ that is **compatible** with every operation: for each $f \in \Sigma$ of arity $n$,
$$\bigl(a_1 \mathrel{\theta} b_1 \ \wedge\ \cdots \ \wedge\ a_n \mathrel{\theta} b_n\bigr) \ \Longrightarrow\ f^{\mathbf A}(a_1, \dots, a_n) \mathrel{\theta} f^{\mathbf A}(b_1, \dots, b_n).$$
The **congruence class** of $a$ is its equivalence class $a/\theta := \{x \in A : a \mathrel{\theta} x\}$. The diagonal $\Delta = \{(a,a) : a \in A\}$ and the full relation $A \times A$ are always congruences (the **trivial** ones).`,
    proof: String.raw`**The kernel of a homomorphism is a congruence.** For $h : \mathbf A \to \mathbf B$ define $\ker h := \{(a, b) \in A \times A : h(a) = h(b)\}$. It is an **equivalence relation** (it is the pullback of equality on $B$, which is reflexive, symmetric, transitive). For compatibility, suppose $a_i \mathrel{(\ker h)} b_i$ for $i = 1, \dots, n$, i.e. $h(a_i) = h(b_i)$. Then by the **homomorphism** law, $h(f^{\mathbf A}(a_1, \dots, a_n)) = f^{\mathbf B}(h(a_1), \dots, h(a_n)) = f^{\mathbf B}(h(b_1), \dots, h(b_n)) = h(f^{\mathbf A}(b_1, \dots, b_n))$, so the two outputs are $\ker h$-related. Hence $\ker h$ is a congruence. $\square$`,
  },
  {
    id: 'quotient-algebra',
    label: 'Quotient Algebra',
    title: 'Quotient Algebra',
    kind: 'definition',
    tags: ['Universal Algebra'],
    dependencies: ['congruence-relation', 'quotient-set', 'algebra-homomorphism'],
    description: String.raw`Given a congruence on an algebra, the **quotient algebra** is formed on the set of congruence classes by operating representative-wise — exactly as one adds residue classes modulo $n$, or multiplies cosets in a quotient group. Compatibility of the congruence is precisely what makes this well defined, independent of the chosen representatives. The natural map sending each element to its class is a surjective homomorphism whose kernel is the original congruence, so congruences and quotients are two views of the same thing.`,
    definition: String.raw`Let $\theta$ be a **congruence** on an algebra $\mathbf{A}$ of signature $\Sigma$. The **quotient algebra** $\mathbf{A}/\theta$ has carrier the **quotient set** $A/\theta = \{a/\theta : a \in A\}$, with operations defined on classes by
$$f^{\mathbf{A}/\theta}(a_1/\theta, \dots, a_n/\theta) := f^{\mathbf A}(a_1, \dots, a_n)/\theta \qquad (f \in \Sigma,\ n = \mathrm{ar}(f)).$$
The **natural map** (canonical projection) is $\pi_\theta : \mathbf{A} \to \mathbf{A}/\theta$, $a \mapsto a/\theta$.`,
    proof: String.raw`**The operations are well defined and $\pi_\theta$ is a surjective homomorphism with $\ker\pi_\theta = \theta$.** Well-definedness is exactly **compatibility** of $\theta$: if $a_i/\theta = b_i/\theta$ for all $i$, i.e. $a_i \mathrel{\theta} b_i$, then $f^{\mathbf A}(a_1, \dots, a_n) \mathrel{\theta} f^{\mathbf A}(b_1, \dots, b_n)$, so the two purported values $f^{\mathbf A}(\bar a)/\theta$ and $f^{\mathbf A}(\bar b)/\theta$ are the same **equivalence class**. Thus $f^{\mathbf{A}/\theta}$ is a genuine function $(A/\theta)^n \to A/\theta$, and $\mathbf{A}/\theta$ is an algebra of signature $\Sigma$. The map $\pi_\theta$ is surjective by construction of the **quotient set**, and it is a **homomorphism**: $\pi_\theta(f^{\mathbf A}(a_1, \dots, a_n)) = f^{\mathbf A}(a_1, \dots, a_n)/\theta = f^{\mathbf{A}/\theta}(a_1/\theta, \dots, a_n/\theta) = f^{\mathbf{A}/\theta}(\pi_\theta a_1, \dots, \pi_\theta a_n)$. Finally $a \mathrel{(\ker\pi_\theta)} b \iff a/\theta = b/\theta \iff a \mathrel{\theta} b$, so $\ker\pi_\theta = \theta$. $\square$`,
  },
  {
    id: 'homomorphism-theorem-ua',
    label: 'Homomorphism Theorem',
    title: 'Homomorphism Theorem (First Isomorphism Theorem)',
    kind: 'theorem',
    tags: ['Universal Algebra'],
    dependencies: ['quotient-algebra', 'congruence-relation', 'algebra-homomorphism', 'isomorphism-theorems'],
    description: String.raw`Every homomorphic image is a quotient: dividing an algebra by the kernel of a homomorphism produces an algebra isomorphic to the image. This single statement, proved once at the level of universal algebra, specializes to the first isomorphism theorems for groups, rings, modules, and lattices simultaneously — the kernel is a congruence rather than a normal subgroup or ideal, but the bookkeeping is identical. It expresses that a surjective homomorphism is, up to isomorphism, nothing but a canonical projection onto a quotient.`,
    statement: String.raw`Let $h : \mathbf{A} \to \mathbf{B}$ be a homomorphism of algebras of signature $\Sigma$. Then $\ker h$ is a congruence on $\mathbf{A}$, and there is a unique isomorphism
$$\bar h : \mathbf{A}/\ker h \ \xrightarrow{\ \cong\ }\ h(\mathbf{A}), \qquad a/\ker h \mapsto h(a),$$
onto the image, satisfying $\bar h \circ \pi_{\ker h} = h$.`,
    proof: String.raw`Write $\theta = \ker h$, a **congruence** on $\mathbf A$, so the **quotient algebra** $\mathbf A/\theta$ and projection $\pi_\theta$ exist. Define $\bar h(a/\theta) := h(a)$.

*Well defined and injective.* If $a/\theta = a'/\theta$ then $a \mathrel\theta a'$, i.e. $h(a) = h(a')$, so the value does not depend on the representative; conversely $\bar h(a/\theta) = \bar h(a'/\theta)$ means $h(a) = h(a')$, i.e. $a \mathrel\theta a'$, i.e. $a/\theta = a'/\theta$. So $\bar h$ is well defined and injective.

*Homomorphism.* For $f \in \Sigma$ of arity $n$, using the operation on the quotient and that $h$ is a **homomorphism**,
$$\bar h\bigl(f^{\mathbf A/\theta}(a_1/\theta, \dots, a_n/\theta)\bigr) = \bar h\bigl(f^{\mathbf A}(\bar a)/\theta\bigr) = h(f^{\mathbf A}(\bar a)) = f^{\mathbf B}(h(a_1), \dots, h(a_n)) = f^{\mathbf B}(\bar h(a_1/\theta), \dots, \bar h(a_n/\theta)).$$

*Onto the image, and isomorphism.* By construction the range of $\bar h$ is $h(A)$, which is a **subalgebra** $h(\mathbf A) \le \mathbf B$; so $\bar h : \mathbf A/\theta \to h(\mathbf A)$ is a bijective homomorphism, hence an isomorphism. Uniqueness and the factorization $\bar h \circ \pi_\theta = h$ hold because $\bar h(\pi_\theta(a)) = \bar h(a/\theta) = h(a)$ and $\pi_\theta$ is surjective, so any map factoring $h$ through $\pi_\theta$ must agree with $\bar h$ on every class. Specializing $\Sigma$ to the group signature recovers the classical **isomorphism theorems**, with $\ker h$ corresponding to the normal subgroup $h^{-1}(e)$. $\square$`,
  },

  // ── Products & free algebras ───────────────────────────────────────────────
  {
    id: 'direct-product-algebra',
    label: 'Direct Product',
    title: 'Direct Product of Algebras',
    kind: 'definition',
    tags: ['Universal Algebra'],
    dependencies: ['algebraic-signature', 'algebra-homomorphism', 'cartesian-product'],
    description: String.raw`The **direct product** of a family of algebras is built on the Cartesian product of their carriers, with every operation applied coordinate-wise. The familiar direct products of groups, rings, and lattices are all instances. Each projection onto a factor is a homomorphism, and the product has the expected universal property: a homomorphism into the product is the same data as a family of homomorphisms into the factors. Products are one of the three operations — alongside subalgebras and homomorphic images — out of which varieties are closed.`,
    definition: String.raw`Let $(\mathbf{A}_i)_{i \in I}$ be a family of algebras of a common signature $\Sigma$. Their **direct product** $\prod_{i \in I} \mathbf{A}_i$ has carrier the Cartesian product $\prod_{i \in I} A_i$ (functions $a : I \to \bigcup_i A_i$ with $a(i) \in A_i$), with operations computed **coordinatewise**: for $f \in \Sigma$ of arity $n$ and tuples $a^{(1)}, \dots, a^{(n)}$,
$$f^{\prod \mathbf A_i}(a^{(1)}, \dots, a^{(n)})(i) := f^{\mathbf{A}_i}\bigl(a^{(1)}(i), \dots, a^{(n)}(i)\bigr) \qquad (i \in I).$$
The **projection** $\pi_j : \prod_i \mathbf{A}_i \to \mathbf{A}_j$, $a \mapsto a(j)$, is defined for each $j \in I$.`,
    proof: String.raw`**Each projection is a homomorphism, and the product has the universal property.** For $f \in \Sigma$ of arity $n$, $\pi_j\bigl(f^{\prod \mathbf A_i}(a^{(1)}, \dots, a^{(n)})\bigr) = f^{\prod \mathbf A_i}(a^{(1)}, \dots, a^{(n)})(j) = f^{\mathbf A_j}(a^{(1)}(j), \dots, a^{(n)}(j)) = f^{\mathbf A_j}(\pi_j a^{(1)}, \dots, \pi_j a^{(n)})$ by the coordinatewise definition, so $\pi_j$ is a **homomorphism**. Given any algebra $\mathbf C$ and homomorphisms $g_i : \mathbf C \to \mathbf A_i$, the map $g : C \to \prod_i A_i$ with $g(c)(i) := g_i(c)$ satisfies $\pi_i \circ g = g_i$, and it is a homomorphism since coordinate $i$ of $g(f^{\mathbf C}(\bar c))$ is $g_i(f^{\mathbf C}(\bar c)) = f^{\mathbf A_i}(g_i \bar c) = f^{\mathbf A_i}((g\bar c)(i))$, matching $f^{\prod \mathbf A_i}(g\bar c)(i)$; it is the unique such map because its coordinates are forced by $\pi_i \circ g = g_i$. $\square$`,
  },
  {
    id: 'term-algebra',
    label: 'Term Algebra',
    title: 'Terms & the Term Algebra',
    kind: 'definition',
    tags: ['Universal Algebra'],
    dependencies: ['algebraic-signature', 'algebra-homomorphism', 'natural-numbers'],
    description: String.raw`A **term** over a set of variables is a formal expression built from variables and operation symbols — like $x \cdot (y \cdot z)$ before any meaning is assigned. The terms themselves form an algebra, the **term algebra**, where each operation symbol acts by literally building the corresponding expression. Its defining feature is *absolute freedom*: any assignment of values to the variables extends in exactly one way to a homomorphism evaluating every term. This evaluation map is how a term names an operation in any algebra, and it is the syntactic engine behind identities and free algebras.`,
    definition: String.raw`Fix a signature $\Sigma$ and a set $X$ of **variables**. The set $T_\Sigma(X)$ of **terms** is generated inductively: every variable $x \in X$ is a term, every constant $c \in \Sigma$ (arity $0$) is a term, and if $t_1, \dots, t_n$ are terms and $f \in \Sigma$ has arity $n \ge 1$ then the string $f(t_1, \dots, t_n)$ is a term; nothing else is. The **term algebra** $\mathbf{T}_\Sigma(X)$ has carrier $T_\Sigma(X)$ with operations $f^{\mathbf T}(t_1, \dots, t_n) := f(t_1, \dots, t_n)$ (and constants interpreted as themselves). Given an algebra $\mathbf A$ and an **assignment** $v : X \to A$, the **value** $t^{\mathbf A}[v] \in A$ of a term is defined by structural recursion matching the three generation clauses: $x^{\mathbf A}[v] = v(x)$ for a variable, $c^{\mathbf A}[v] = c^{\mathbf A}$ for a constant $c \in \Sigma$ (arity $0$), and $f(t_1, \dots, t_n)^{\mathbf A}[v] = f^{\mathbf A}(t_1^{\mathbf A}[v], \dots, t_n^{\mathbf A}[v])$ for $f \in \Sigma$ of arity $n \ge 1$.`,
    proof: String.raw`**Universal mapping property: every assignment $v : X \to A$ extends to a unique homomorphism $\hat v : \mathbf T_\Sigma(X) \to \mathbf A$.** Define $\hat v(t) := t^{\mathbf A}[v]$. This is a **homomorphism**: for $f \in \Sigma$ of arity $n$, by the recursive value clause $\hat v(f^{\mathbf T}(t_1, \dots, t_n)) = \hat v(f(t_1, \dots, t_n)) = f(t_1, \dots, t_n)^{\mathbf A}[v] = f^{\mathbf A}(t_1^{\mathbf A}[v], \dots, t_n^{\mathbf A}[v]) = f^{\mathbf A}(\hat v t_1, \dots, \hat v t_n)$, and constants and variables are handled by the base clauses. It extends $v$ since $\hat v(x) = v(x)$. Uniqueness is structural induction: any homomorphism $g$ with $g\!\restriction_X = v$ agrees with $\hat v$ on variables and constants, and if $g(t_i) = \hat v(t_i)$ for all $i$ then $g(f(t_1, \dots, t_n)) = f^{\mathbf A}(g t_1, \dots, g t_n) = f^{\mathbf A}(\hat v t_1, \dots, \hat v t_n) = \hat v(f(t_1, \dots, t_n))$. Since every term is reached by the inductive clauses, $g = \hat v$. $\square$`,
  },
  {
    id: 'free-algebra',
    label: 'Free Algebra',
    title: 'Free Algebra in a Class',
    kind: 'definition',
    tags: ['Universal Algebra'],
    dependencies: ['term-algebra', 'congruence-relation', 'quotient-algebra', 'subalgebra', 'direct-product-algebra'],
    description: String.raw`A **free algebra** on a set of generators is the most general algebra those generators can produce inside a given class: every map from the generators into any algebra of the class extends uniquely to a homomorphism. For the class of *all* algebras the free algebra is the term algebra; for a class defined by identities one must quotient the term algebra by the congruence forcing exactly those identities to hold and nothing more. Free groups, free monoids (words under concatenation), and polynomial rings are the standard examples, and free algebras are the device through which Birkhoff's theorems are proved.`,
    definition: String.raw`Let $\mathcal{K}$ be a class of algebras of signature $\Sigma$ and $X$ a set. An algebra $\mathbf{F} \in \mathcal{K}$ together with a map $\iota : X \to F$ is **free over $X$ in $\mathcal{K}$** if for every $\mathbf{A} \in \mathcal{K}$ and every map $v : X \to A$ there is a *unique* homomorphism $\hat v : \mathbf{F} \to \mathbf{A}$ with $\hat v \circ \iota = v$. Concretely one realizes it as $\mathbf{F}_{\mathcal K}(X) := \mathbf{T}_\Sigma(X)/\theta_{\mathcal K}$, where
$$\theta_{\mathcal K} := \bigcap\,\{\,\ker(\hat v) : \mathbf A \in \mathcal{K},\ v : X \to A\,\}$$
is the intersection of the kernels of all evaluation homomorphisms out of the **term algebra**, and $\iota(x) = x/\theta_{\mathcal K}$.`,
    proof: String.raw`**$\theta_{\mathcal K}$ is a congruence and $\mathbf F_{\mathcal K}(X)$ has the universal property, provided $\mathcal K$ is closed under subalgebras and products.** An intersection of **congruences** is a congruence (compatibility and the equivalence laws are preserved under intersection), so $\theta_{\mathcal K}$ is a congruence on $\mathbf T_\Sigma(X)$ and the **quotient algebra** $\mathbf F = \mathbf T_\Sigma(X)/\theta_{\mathcal K}$ exists. To see $\mathbf F \in \mathcal K$ one must take care that $\mathcal K$ may be a *proper class* (e.g. all groups), so the family of all pairs $(\mathbf A, v)$ with $\mathbf A \in \mathcal K$ is not a set and "$\prod_{(\mathbf A, v)} \mathbf A$" over it is not an algebra. Restrict to a *set* of representatives. Each evaluation map $\hat v_0 : \mathbf T_\Sigma(X) \to \mathbf A$ factors through its image $\hat v_0(\mathbf T_\Sigma(X))$, a **subalgebra** of $\mathbf A$ generated by $v(X)$ and hence of cardinality $\le |T_\Sigma(X)|$, with $\ker \hat v_0$ equal to the kernel of the corestriction onto that image; so the value of $\theta_{\mathcal K}$ is unchanged if the intersection ranges only over pairs $(\mathbf A, v)$ in which $\mathbf A \in \mathcal K$ is generated by $v(X)$, whence $|A| \le |T_\Sigma(X)|$. Up to isomorphism there is only a *set* $R$ of such algebras (one representative per carrier-size $\le |T_\Sigma(X)|$ and choice of operations), so the index family $\{(\mathbf A, v) : \mathbf A \in R,\ v : X \to A\}$ is a set. Then $\mathbf F$ embeds, via $t/\theta_{\mathcal K} \mapsto (\hat v(t))_{(\mathbf A, v)}$, into the set-indexed **direct product** $\prod_{(\mathbf A, v)} \mathbf A$ of members of $\mathcal K$ (well defined and injective exactly because $\theta_{\mathcal K}$ is the common kernel), exhibiting $\mathbf F$ as a subalgebra of a product of members of $\mathcal K$; closure under products and subalgebras gives $\mathbf F \in \mathcal K$. For the universal property, given $\mathbf A \in \mathcal K$ and $v : X \to A$, the **term algebra** gives $\hat v_0 : \mathbf T_\Sigma(X) \to \mathbf A$ extending $v$; since $\theta_{\mathcal K} \subseteq \ker \hat v_0$, it factors through the projection as a unique $\hat v : \mathbf F \to \mathbf A$ with $\hat v(t/\theta_{\mathcal K}) = \hat v_0(t)$, whence $\hat v(\iota(x)) = v(x)$, and uniqueness follows since $\iota(X)$ generates $\mathbf F$. $\square$`,
  },

  // ── Identities & varieties ─────────────────────────────────────────────────
  {
    id: 'identity-equational-class',
    label: 'Identity & Eq. Class',
    title: 'Identities and Equational Classes',
    kind: 'definition',
    tags: ['Universal Algebra'],
    dependencies: ['term-algebra', 'algebra-homomorphism'],
    description: String.raw`An **identity** is an equation between two terms that is asserted to hold for *all* values of its variables — associativity $x \cdot (y \cdot z) = (x \cdot y) \cdot z$ is the archetype. An algebra **satisfies** an identity when both sides evaluate equally under every assignment. Fixing a set of identities and collecting all algebras that satisfy them yields an **equational class**: groups, rings, lattices, and Boolean algebras are each defined this way. Satisfaction is invariant under homomorphic images, subalgebras, and products — the closure properties that Birkhoff's HSP theorem shows are exactly characteristic of equational classes.`,
    definition: String.raw`Fix a signature $\Sigma$ and variables $X$. An **identity** (equation) is a pair of **terms** $s, t \in T_\Sigma(X)$, written $s \approx t$. An algebra $\mathbf{A}$ **satisfies** $s \approx t$, written $\mathbf{A} \models s \approx t$, if $s^{\mathbf A}[v] = t^{\mathbf A}[v]$ for *every* assignment $v : X \to A$. For a set $E$ of identities, $\mathbf A \models E$ means $\mathbf A$ satisfies every member, and the **equational class** (or **model class**) is
$$\mathrm{Mod}(E) := \{\,\mathbf A : \mathbf A \models E\,\}.$$
A class $\mathcal{K}$ is **equationally definable** if $\mathcal{K} = \mathrm{Mod}(E)$ for some set $E$ of identities.`,
    proof: String.raw`**Satisfaction of an identity transfers along surjective homomorphisms.** Let $h : \mathbf A \to \mathbf B$ be a surjective **homomorphism** and suppose $\mathbf A \models s \approx t$. A first induction on term structure shows $h$ commutes with term evaluation: $h(r^{\mathbf A}[v]) = r^{\mathbf B}[h \circ v]$ for every term $r$ and assignment $v : X \to A$ — the base cases are $h(v(x)) = (h\circ v)(x)$ and the constant clause, and the inductive step is the homomorphism law applied to $f$. Now take any assignment $w : X \to B$; by surjectivity choose $v : X \to A$ with $h \circ v = w$ (pick a preimage of each $w(x)$). Then $s^{\mathbf B}[w] = s^{\mathbf B}[h\circ v] = h(s^{\mathbf A}[v]) = h(t^{\mathbf A}[v]) = t^{\mathbf B}[h \circ v] = t^{\mathbf B}[w]$, using $\mathbf A \models s \approx t$ in the middle. As $w$ was arbitrary, $\mathbf B \models s \approx t$. $\square$`,
  },
  {
    id: 'variety',
    label: 'Variety',
    title: 'Variety (HSP-Closed Class)',
    kind: 'definition',
    tags: ['Universal Algebra'],
    dependencies: ['subalgebra', 'algebra-homomorphism', 'direct-product-algebra'],
    description: String.raw`A **variety** is a class of algebras closed under the three fundamental constructions: taking **homomorphic images** (H), **subalgebras** (S), and **direct products** (P). This is a purely structural definition — it never mentions equations — yet Birkhoff's theorem reveals that the varieties are exactly the equationally definable classes. The closure operators H, S, P generate, from any class, the smallest variety containing it, and the interplay of these operators (captured by inclusions such as $SH \subseteq HS$, $PS \subseteq SP$, $PH \subseteq HP$) is the combinatorial heart of the subject.`,
    definition: String.raw`Let $\mathcal{K}$ be a class of algebras of signature $\Sigma$. Write $H(\mathcal K)$ for the class of all **homomorphic images** of members of $\mathcal K$, $S(\mathcal K)$ for all (isomorphic copies of) **subalgebras** of members, and $P(\mathcal K)$ for all **direct products** of families of members. The class $\mathcal K$ is a **variety** if it is closed under all three:
$$H(\mathcal K) \subseteq \mathcal K, \qquad S(\mathcal K) \subseteq \mathcal K, \qquad P(\mathcal K) \subseteq \mathcal K.$$
The **variety generated by** $\mathcal K$ is the smallest variety containing it, denoted $V(\mathcal K)$.`,
    proof: String.raw`**$HSP(\mathcal K)$ is a variety, and is the smallest one containing $\mathcal K$ — so $V(\mathcal K) = HSP(\mathcal K)$.** Each of $H, S, P$ is *extensive* ($\mathcal K \subseteq O(\mathcal K)$, since an algebra is its own image/subalgebra/one-factor product) and *monotone*. A class is a **variety** iff it is a fixed point of all three. From the standard operator inequalities $SH \le HS$, $PS \le SP$, $PH \le HP$ (each says one construction can be pushed past another: e.g. a subalgebra of a homomorphic image is a homomorphic image of a subalgebra), together with idempotence $HH = H$, $SS = S$, $PP = P$, one verifies $H(HSP) \le HSP$, $S(HSP) = SHSP \le HSSP = HSP$, and $P(HSP) = PHSP \le HPSP \le HSPP \le HSP$. Hence $HSP(\mathcal K)$ is closed under H, S, and P, i.e. a variety, and it contains $\mathcal K$. Any variety $\mathcal W \supseteq \mathcal K$ satisfies $HSP(\mathcal W) \subseteq \mathcal W$ by closure and monotonicity gives $HSP(\mathcal K) \subseteq HSP(\mathcal W) \subseteq \mathcal W$; so $HSP(\mathcal K)$ is least. $\square$`,
  },
  {
    id: 'birkhoff-hsp-theorem',
    label: 'Birkhoff HSP',
    title: 'Birkhoff Variety (HSP) Theorem',
    kind: 'theorem',
    tags: ['Universal Algebra'],
    dependencies: ['variety', 'identity-equational-class', 'free-algebra', 'direct-product-algebra', 'subalgebra'],
    description: String.raw`Birkhoff's theorem is the foundational bridge between syntax and structure in universal algebra: a class of algebras is definable by identities **if and only if** it is closed under homomorphic images, subalgebras, and direct products. One direction is an easy preservation argument; the deep direction builds, from any HSP-closed class, the precise set of identities it satisfies and recovers the class as their models, the key tool being the free algebra on a countably infinite set of variables. The theorem is why "the equationally axiomatizable classes" and "the varieties" are interchangeable phrases, and it launches the structural study of varieties.`,
    statement: String.raw`A class $\mathcal{K}$ of algebras of signature $\Sigma$ is a **variety** (closed under $H$, $S$, $P$) if and only if it is an **equational class**: $\mathcal{K} = \mathrm{Mod}(E)$ for some set $E$ of identities. Equivalently, $\mathrm{Mod}$ and $\mathrm{Id}$ — where $\mathrm{Id}(\mathcal K)$ is the set of all identities holding in every member of $\mathcal K$ — restrict to a bijection between varieties and sets of identities closed under deduction, with $V(\mathcal K) = \mathrm{Mod}(\mathrm{Id}(\mathcal K))$.`,
    proof: String.raw`**($\Leftarrow$, soundness — fully proved here.)** Let $\mathcal K = \mathrm{Mod}(E)$. Closure under products: if each $\mathbf A_i \models s \approx t$, then evaluating in $\prod_i \mathbf A_i$ is coordinatewise (**direct product**), so $s \approx t$ holds in the product; closure under subalgebras is immediate as term values in a **subalgebra** agree with those in the ambient algebra; closure under homomorphic images is the transfer lemma proved in **identity-equational-class**. Hence $\mathrm{Mod}(E)$ is closed under $H, S, P$: a variety.

**($\Rightarrow$, completeness — *sketch, naming the external inputs*.)** Let $\mathcal K$ be a variety; put $E = \mathrm{Id}(\mathcal K)$, the identities true throughout $\mathcal K$. Clearly $\mathcal K \subseteq \mathrm{Mod}(E)$; the content is the reverse inclusion $\mathrm{Mod}(E) \subseteq \mathcal K$. Given $\mathbf B \in \mathrm{Mod}(E)$, fix a generating set $Y$ of $\mathbf B$ and form the **free algebra** $\mathbf F = \mathbf F_{\mathcal K}(Y)$ on a set of generators of the *same rank* $|Y|$, which lies in $\mathcal K$ because $\mathcal K$, being closed under $S$ and $P$, contains it (the construction in **free-algebra** realizes $\mathbf F$ as a subalgebra of a product of members of $\mathcal K$). The identity-on-$Y$ map and the universal property of $\mathbf F$ yield a surjective homomorphism $\mathbf F \twoheadrightarrow \mathbf B$, so $\mathbf B \in H(\mathbf F) \subseteq H(\mathcal K) = \mathcal K$. The two inclusions give $\mathcal K = \mathrm{Mod}(E)$.

The step taken on faith is the **relatively-free-algebra characterization** of Birkhoff: that for the variety $\mathcal K$ the free algebra $\mathbf F_{\mathcal K}(Y)$ satisfies *exactly* the identities of $E = \mathrm{Id}(\mathcal K)$, so that the only relations holding among the generators of $\mathbf B \in \mathrm{Mod}(E)$ are consequences of $E$ and the map $\mathbf F_{\mathcal K}(Y) \twoheadrightarrow \mathbf B$ is therefore well defined. This — together with the existence of $\mathbf F_{\mathcal K}(Y)$ in $\mathcal K$ at arbitrary rank — has no separate node here and is taken as a cited classical result rather than reproven in full. $\square$`,
  },

  // ── Equational logic ───────────────────────────────────────────────────────
  {
    id: 'equational-logic',
    label: 'Equational Logic',
    title: 'Equational Logic & Derivability',
    kind: 'definition',
    tags: ['Universal Algebra'],
    dependencies: ['identity-equational-class', 'term-algebra', 'first-order-logic'],
    description: String.raw`**Equational logic** is the proof calculus for identities: a purely syntactic way to derive new equations from old ones using five rules — reflexivity, symmetry, transitivity, substitution of terms for variables, and replacement of equals within a larger term (congruence). It is the fragment of first-order logic in which the only formulas are universally quantified equations. Writing $E \vdash s \approx t$ when $s \approx t$ is derivable from a set $E$ of axioms gives a finitary, mechanical notion of equational proof, complementary to the semantic notion of an identity holding in all models.`,
    definition: String.raw`Fix a signature $\Sigma$ and variables $X$. The **derivability** relation $E \vdash s \approx t$ between a set $E$ of identities and an identity $s \approx t$ (with $s, t \in T_\Sigma(X)$) is the least relation closed under: **(axioms)** $E \vdash s \approx t$ for each $s \approx t \in E$; **(reflexivity)** $E \vdash t \approx t$; **(symmetry)** from $E \vdash s \approx t$ infer $E \vdash t \approx s$; **(transitivity)** from $E \vdash r \approx s$ and $E \vdash s \approx t$ infer $E \vdash r \approx t$; **(substitution)** from $E \vdash s \approx t$ infer $E \vdash s\sigma \approx t\sigma$ for any substitution $\sigma$ replacing variables by terms; and **(congruence/replacement)** from $E \vdash s_i \approx t_i$ ($i = 1, \dots, n$) infer $E \vdash f(s_1, \dots, s_n) \approx f(t_1, \dots, t_n)$ for each $f \in \Sigma$ of arity $n$. These are exactly the equational rules within **first-order logic** with equality.`,
  },
  {
    id: 'birkhoff-completeness-theorem',
    label: 'Birkhoff Completeness',
    title: 'Birkhoff Completeness of Equational Logic',
    kind: 'theorem',
    tags: ['Universal Algebra'],
    dependencies: ['equational-logic', 'identity-equational-class', 'term-algebra', 'congruence-relation', 'quotient-algebra', 'equivalence-relation'],
    description: String.raw`Equational logic is *complete*: an identity is provable from a set of equational axioms exactly when it holds in every model of those axioms. Soundness — that the five rules only derive valid consequences — is routine. The converse is Birkhoff's completeness theorem, proved by a term-model construction: the term algebra modulo provable equality is itself a model of the axioms, so any unprovable equation fails in it. This matches, for the equational fragment, Gödel's completeness theorem for full first-order logic, and it guarantees the proof calculus captures equational consequence with nothing left out.`,
    statement: String.raw`Let $E$ be a set of identities over a signature $\Sigma$. For all terms $s, t$,
$$E \vdash s \approx t \quad\Longleftrightarrow\quad \mathrm{Mod}(E) \models s \approx t,$$
i.e. $s \approx t$ is derivable in **equational logic** from $E$ if and only if $s \approx t$ holds in every algebra satisfying $E$. (Here $\mathrm{Mod}(E) \models s \approx t$ means $\mathbf A \models s \approx t$ for every $\mathbf A \models E$.)`,
    proof: String.raw`**($\Rightarrow$) Soundness, fully proved.** Suppose $E \vdash s \approx t$ and let $\mathbf A \models E$; we show $\mathbf A \models s \approx t$ by induction on the derivation. Each axiom holds in $\mathbf A$ by hypothesis. Reflexivity, symmetry, and transitivity hold because $=$ on $A$ is an equivalence relation, applied pointwise over assignments. Substitution: if $\mathbf A \models s \approx t$ and $\sigma$ replaces variables by terms, then for any assignment $v$ the value $(s\sigma)^{\mathbf A}[v] = s^{\mathbf A}[v']$ where $v'(x) = (\sigma x)^{\mathbf A}[v]$ (a standard substitution-value identity), and likewise for $t\sigma$; equality of the two follows from $\mathbf A \models s \approx t$ at the assignment $v'$. Congruence: if $\mathbf A \models s_i \approx t_i$ then for each $v$, $f^{\mathbf A}(s_1^{\mathbf A}[v], \dots) = f^{\mathbf A}(t_1^{\mathbf A}[v], \dots)$ since $f^{\mathbf A}$ is a function, i.e. $\mathbf A \models f(\bar s) \approx f(\bar t)$. So every derivable identity is satisfied.

**($\Leftarrow$) Completeness, via the term model.** Define $s \mathrel{\sim_E} t :\iff E \vdash s \approx t$ on $T_\Sigma(X)$ for a sufficiently large variable set $X$. The reflexivity/symmetry/transitivity rules make $\sim_E$ an **equivalence relation**, and the congruence rule makes it compatible with every $f \in \Sigma$, so $\sim_E$ is a **congruence** on the **term algebra** $\mathbf T_\Sigma(X)$. Form the **quotient algebra** $\mathbf F_E := \mathbf T_\Sigma(X)/{\sim_E}$. *Claim:* $\mathbf F_E \models E$. For an axiom $u \approx w \in E$ and any assignment $v : X \to F_E$, lift $v$ to terms via representatives and use the substitution rule: $E \vdash u\sigma \approx w\sigma$ where $\sigma$ realizes $v$, so $u^{\mathbf F_E}[v] = (u\sigma)/{\sim_E} = (w\sigma)/{\sim_E} = w^{\mathbf F_E}[v]$; hence $\mathbf F_E \models u \approx w$, and $\mathbf F_E \models E$. Now suppose $\mathrm{Mod}(E) \models s \approx t$. Since $\mathbf F_E \in \mathrm{Mod}(E)$, in particular $\mathbf F_E \models s \approx t$; evaluating at the assignment $v_0(x) = x/{\sim_E}$ (so that $r^{\mathbf F_E}[v_0] = r/{\sim_E}$ for every term $r$, by induction on $r$) gives $s/{\sim_E} = t/{\sim_E}$, i.e. $E \vdash s \approx t$. This is the converse, completing the equivalence. $\square$`,
  },
]
